
// Generated helper templates
// Generated items
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CustomerFeedbackExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\WebPageExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\WebMenuCategoryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\WebMenuExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\WebElementTypeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\WebElementExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\WebCustomerFeedbackExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\WardExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\VoucherExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ViewCounterExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\VATOrderMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\VATOrderExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\UserExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TransactionExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TokenUserExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TimeModeTypeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TimeModeRuleExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TimeFrameExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ThemeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TemplateRuleMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TemplateReportProductItemMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TemplateDetailMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TagMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\TagExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\SystemPartnerMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\sysdiagramExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\SubRentGroupExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreWebViewCounterExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreWebSettingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreWebRouteModelExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreWebRouteExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreUserExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreThemeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreGroupMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreGroupExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreDomainExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\StoreExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\SalaryRuleExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\SalaryHourExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\RoomFloorExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\RoomCategoryPriceGroupMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\RoomCategoryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\RoomExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\RoleExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ReportTrackingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\RatingStarExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\RatingProductExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProvinceExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProviderProductItemMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProviderExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PromotionStoreMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PromotionDetailExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PromotionExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProfileExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductSpecificationExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductItemCompositionMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductItemCategoryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductImageCollectionItemMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductImageCollectionExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductImageExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductDetailMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductComboDetailExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductCollectionItemMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductCollectionExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductCategoryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ProductExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PriceNightExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PriceGroupExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PriceAdditionExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PosFileExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PosConfigExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PosExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PaySlipTemplateExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PaySlipItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PayslipAttributeMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PayslipAttributeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PaySlipExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PayrollPeriodExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PayrollDetailExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PayrollCategoryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PaymentReportExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PaymentPartnerExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PaymentExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PartnerMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\PartnerExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\OrderPromotionMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\OrderGroupExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\OrderFeeItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\OrderDetailPromotionMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\OrderDetailExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\OrderExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\NotificationExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\MenuExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\MembershipCardTypeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\MembershipCardExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\MachineConnectExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\LanguageValueExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\LanguageKeyExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\LanguageExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\InventoryTemplateReportExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\InventoryReceiptItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\InventoryReceiptExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\InventoryDateReportItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\InventoryDateReportExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\InventoryCheckingItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\InventoryCheckingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ImageCollectionItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ImageCollectionExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\GuestExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\GroupExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\FingerScanMachineExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\FavoritedExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\EventLocationExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\EmployeeInStoreExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\EmployeeGroupExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\EmployeeFingerExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\EmployeeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DistrictExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DeviceExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DeliveryInformationExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DeliveryInfoExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DayModeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DateReportExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DateProductItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DateProductExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\DateHotelReportExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CustomerTypeExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CustomerStoreReportMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CustomerProductMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CustomerFilterExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CustomerExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CouponProviderExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CouponCampaignExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CouponExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CostInventoryMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CostCategoryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CostExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ContactExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CheckFingerExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CategoryExtraMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\CategoryExtraExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\BrandExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\BlogPostImageExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\BlogPostCollectionItemMappingExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\BlogPostCollectionItemExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\BlogPostCollectionExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\BlogPostExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\BlogCategoryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\AttendanceDateExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\AttendanceExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\AspNetUserExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\AspNetUserLoginExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\AspNetUserClaimExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\AspNetRoleExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ArticleExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\AreaDeliveryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\ApplicationExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\AccountExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\C__MigrationHistoryExtensionGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Extensions\EntityGen.cs
