
// Generated helper templates
// Generated items
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CustomerFeedbackRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\WebPageRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\WebMenuCategoryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\WebMenuRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\WebElementTypeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\WebElementRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\WebCustomerFeedbackRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\WardRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\VoucherRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ViewCounterRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\VATOrderMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\VATOrderRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\UserRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TransactionRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TokenUserRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TimeModeTypeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TimeModeRuleRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TimeFrameRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ThemeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TemplateRuleMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TemplateReportProductItemMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TemplateDetailMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TagMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\TagRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\SystemPartnerMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\sysdiagramRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\SubRentGroupRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreWebViewCounterRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreWebSettingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreWebRouteModelRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreWebRouteRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreUserRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreThemeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreGroupMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreGroupRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreDomainRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\StoreRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\SalaryRuleRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\SalaryHourRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\RoomFloorRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\RoomCategoryPriceGroupMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\RoomCategoryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\RoomRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\RoleRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ReportTrackingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\RatingStarRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\RatingProductRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProvinceRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProviderProductItemMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProviderRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PromotionStoreMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PromotionDetailRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PromotionRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProfileRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductSpecificationRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductItemCompositionMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductItemCategoryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductImageCollectionItemMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductImageCollectionRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductImageRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductDetailMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductComboDetailRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductCollectionItemMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductCollectionRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductCategoryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ProductRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PriceNightRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PriceGroupRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PriceAdditionRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PosFileRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PosConfigRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PosRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PaySlipTemplateRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PaySlipItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PayslipAttributeMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PayslipAttributeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PaySlipRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PayrollPeriodRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PayrollDetailRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PayrollCategoryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PaymentReportRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PaymentPartnerRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PaymentRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PartnerMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\PartnerRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\OrderPromotionMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\OrderGroupRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\OrderFeeItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\OrderDetailPromotionMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\OrderDetailRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\OrderRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\NotificationRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\MenuRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\MembershipCardTypeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\MembershipCardRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\MachineConnectRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\LanguageValueRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\LanguageKeyRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\LanguageRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\InventoryTemplateReportRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\InventoryReceiptItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\InventoryReceiptRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\InventoryDateReportItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\InventoryDateReportRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\InventoryCheckingItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\InventoryCheckingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ImageCollectionItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ImageCollectionRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\GuestRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\GroupRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\FingerScanMachineRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\FavoritedRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\EventLocationRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\EmployeeInStoreRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\EmployeeGroupRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\EmployeeFingerRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\EmployeeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DistrictRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DeviceRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DeliveryInformationRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DeliveryInfoRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DayModeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DateReportRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DateProductItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DateProductRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\DateHotelReportRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CustomerTypeRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CustomerStoreReportMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CustomerProductMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CustomerFilterRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CustomerRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CouponProviderRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CouponCampaignRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CouponRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CostInventoryMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CostCategoryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CostRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ContactRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CheckFingerRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CategoryExtraMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\CategoryExtraRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\BrandRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\BlogPostImageRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\BlogPostCollectionItemMappingRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\BlogPostCollectionItemRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\BlogPostCollectionRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\BlogPostRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\BlogCategoryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\AttendanceDateRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\AttendanceRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\AspNetUserRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\AspNetUserLoginRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\AspNetUserClaimRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\AspNetRoleRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ArticleRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\AreaDeliveryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\ApplicationRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\AccountRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Repository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\C__MigrationHistoryRepository.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Repositories\BaseRepository.cs
