using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Json.Serialization;

namespace TNT.Core.WebApi.Postman
{
    [Serializable]
    public class PostmanCollection
    {
        [JsonPropertyName("auth")]
        public virtual Auth Auth { get; set; }
        [JsonPropertyName("protocolProfileBehavior")]
        public virtual ProtocolProfileBehavior ProtocolProfileBehavior { get; set; }
        [JsonPropertyName("info")]
        public virtual Info Info { get; set; } = new Info();
        [JsonPropertyName("item")]
        public virtual List<Item> Item { get; set; }
        [JsonPropertyName("variable")]
        public virtual List<Variable> Variable { get; set; }
    }

    [Serializable]
    public class Info
    {
        [JsonPropertyName("_postman_id")]
        public virtual string PostmanId { get; set; } = Guid.NewGuid().ToString();
        [JsonPropertyName("name")]
        public virtual string Name { get; set; } = "Default";
        [JsonPropertyName("description")]
        public virtual string Description { get; set; } = "This collection is generated by TNT.Core.WebApi";
        [JsonPropertyName("schema")]
        public virtual string Schema { get; set; } = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json";
    }

    [Serializable]
    public class Auth
    {
        [JsonPropertyName("type")]
        public virtual string Type { get; set; }
        [JsonPropertyName("oauth2")]
        public virtual List<OAuth2> OAuth2 { get; set; }
    }

    [Serializable]
    public class OAuth2
    {
        [JsonPropertyName("key")]
        public virtual string Key { get; set; }
        [JsonPropertyName("value")]
        public virtual string Value { get; set; }
        [JsonPropertyName("type")]
        public virtual string Type { get; set; }
    }

    [Serializable]
    public class ProtocolProfileBehavior
    {
    }

    [Serializable]
    public abstract class Item
    {
        [JsonPropertyName("name")]
        public virtual string Name { get; set; }
    }

    [Serializable]
    public class RequestItem : Item
    {
        [JsonPropertyName("request")]
        public virtual Request Request { get; set; }
        [JsonPropertyName("response")]
        public virtual List<object> Response { get; set; }
    }

    [Serializable]
    public class FolderItem : Item
    {
        [JsonPropertyName("auth")]
        public virtual Auth Auth { get; set; }
        [JsonPropertyName("description")]
        public virtual string Description { get; set; }
        [JsonPropertyName("protocolProfileBehavior")]
        public virtual ProtocolProfileBehavior ProtocolProfileBehavior { get; set; }
        [JsonPropertyName("item")]
        public virtual List<Item> Item { get; set; }
    }

    [Serializable]
    public class Request
    {
        [JsonPropertyName("auth")]
        public virtual Auth Auth { get; set; }
        [JsonPropertyName("method")]
        public virtual string Method { get; set; }
        [JsonPropertyName("header")]
        public virtual List<Header> Header { get; set; }
        [JsonPropertyName("body")]
        public virtual Body Body { get; set; }
        [JsonPropertyName("url")]
        public virtual Url Url { get; set; }
        [JsonPropertyName("description")]
        public virtual string Description { get; set; }
    }

    [Serializable]
    public class Body
    {
        [JsonPropertyName("mode")]
        public virtual string Mode { get; set; }
        [JsonPropertyName("raw")]
        public virtual string Raw { get; set; }
        [JsonPropertyName("options")]
        public virtual Options Options { get; set; }
    }

    [Serializable]
    public class Options
    {
        [JsonPropertyName("raw")]
        public virtual Raw Raw { get; set; }
    }

    [Serializable]
    public class Raw
    {
        [JsonPropertyName("language")]
        public virtual string Language { get; set; }
    }

    [Serializable]
    public class Url
    {
        [JsonPropertyName("raw")]
        public virtual string Raw { get; set; }
        [JsonPropertyName("host")]
        public virtual List<string> Host { get; set; }
        [JsonPropertyName("query")]
        public virtual List<Query> Query { get; set; }
    }

    [Serializable]
    public class Query
    {
        [JsonPropertyName("key")]
        public virtual string Key { get; set; }
        [JsonPropertyName("value")]
        public virtual string Value { get; set; }
    }

    [Serializable]
    public class Header
    {
        [JsonPropertyName("key")]
        public virtual string Key { get; set; }
        [JsonPropertyName("value")]
        public virtual string Value { get; set; }
        [JsonPropertyName("type")]
        public virtual string Type { get; set; }
    }

    [Serializable]
    public class Variable
    {
        [JsonPropertyName("id")]
        public virtual string Id { get; set; }
        [JsonPropertyName("key")]
        public virtual string Key { get; set; }
        [JsonPropertyName("value")]
        public virtual string Value { get; set; }
        [JsonPropertyName("type")]
        public virtual string Type { get; set; }
    }

    public enum AuthType
    {
        [Display(Name = "oauth2")]
        OAuth2 = 1,
    }

    public enum OAuth2AddTokenToEnum
    {
        [Display(Name = "header")]
        Header = 1,
    }

    public enum BodyMode
    {
        [Display(Name = "raw")]
        Raw = 1,
    }

    public enum RawLanguage
    {
        [Display(Name = "json")]
        Json = 1,
    }

}
