//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogPostCollection()
        {
            this.BlogPostCollection1 = new HashSet<BlogPostCollection>();
            this.BlogPostCollectionItemMappings = new HashSet<BlogPostCollectionItemMapping>();
            this.BlogPostCollectionItems = new HashSet<BlogPostCollectionItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SeoName { get; set; }
        public int StoreId { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public string SeoDescription { get; set; }
        public string Link { get; set; }
        public string PicUrl { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsDisplay { get; set; }
        public Nullable<int> Position { get; set; }
        public string SeoKeyword { get; set; }
        public int Limitation { get; set; }
        public string SeoName1 { get; set; }
        public int BrandId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPostCollection> BlogPostCollection1 { get; set; }
        public virtual BlogPostCollection BlogPostCollection2 { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPostCollectionItemMapping> BlogPostCollectionItemMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPostCollectionItem> BlogPostCollectionItems { get; set; }
    }
}
