//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogPost()
        {
            this.BlogPostCollectionItemMappings = new HashSet<BlogPostCollectionItemMapping>();
            this.BlogPostImages = new HashSet<BlogPostImage>();
            this.TagMappings = new HashSet<TagMapping>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Title_En { get; set; }
        public string Opening { get; set; }
        public Nullable<int> Opening_En { get; set; }
        public string BlogContent { get; set; }
        public string BlogContent_En { get; set; }
        public bool Active { get; set; }
        public int StoreId { get; set; }
        public string Image { get; set; }
        public string Author { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string SeoName { get; set; }
        public string MetaKeyword { get; set; }
        public Nullable<int> TotalVisit { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int BrandId { get; set; }
        public string Excerpt { get; set; }
        public string URL { get; set; }
        public Nullable<int> BlogCategoryId { get; set; }
        public string PageTitle { get; set; }
        public string PageTitle_En { get; set; }
        public string MetaDescription { get; set; }
        public int Position { get; set; }
        public Nullable<int> Status { get; set; }
        public string LastUpdatePerson { get; set; }
        public string Reference { get; set; }
        public string LinkRef1 { get; set; }
        public string LinkRef2 { get; set; }
        public string LinkRef3 { get; set; }
        public string LinkRef4 { get; set; }
        public string LinkRef5 { get; set; }
        public Nullable<int> BlogType { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string AuthorRefer { get; set; }
        public string UserApprove { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public Nullable<int> BlogPostCollectionNumber { get; set; }
    
        public virtual BlogCategory BlogCategory { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPostCollectionItemMapping> BlogPostCollectionItemMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPostImage> BlogPostImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagMapping> TagMappings { get; set; }
    }
}
