//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogCategory()
        {
            this.BlogPosts = new HashSet<BlogPost>();
            this.TagMappings = new HashSet<TagMapping>();
        }
    
        public int Id { get; set; }
        public string BlogCateName { get; set; }
        public string BlogCateName_EN { get; set; }
        public string PicUrl { get; set; }
        public string BannerUrl { get; set; }
        public string Description { get; set; }
        public string Description_EN { get; set; }
        public string FeedburnerUrl { get; set; }
        public string PageTitle { get; set; }
        public string PageTitle_EN { get; set; }
        public string MetaDescription { get; set; }
        public string UrlHandle { get; set; }
        public string IsAllowComment { get; set; }
        public int StoreId { get; set; }
        public bool IsActive { get; set; }
        public int Type { get; set; }
        public string Feedburner { get; set; }
        public string SeoName { get; set; }
        public string SeoKeyword { get; set; }
        public string SeoDescription { get; set; }
        public string ImageFontAwsomeCss { get; set; }
        public Nullable<int> ParentCateId { get; set; }
        public int Position { get; set; }
        public int PositionTopicHomePage { get; set; }
        public int BrandId { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPost> BlogPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagMapping> TagMappings { get; set; }
    }
}
