//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckFinger
    {
        public int Id { get; set; }
        public Nullable<int> FingerScanMachineId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> Mode { get; set; }
        public bool Active { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string MachineNumber { get; set; }
        public string EmpEnrollNumber { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string LogCode { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FingerScanMachine FingerScanMachine { get; set; }
    }
}
