//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int Id { get; set; }
        public Nullable<int> CampaginId { get; set; }
        public string SerialNumber { get; set; }
        public int Status { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> DateUse { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual CouponCampaign CouponCampaign { get; set; }
    }
}
