//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.CustomerProductMappings = new HashSet<CustomerProductMapping>();
            this.CustomerStoreReportMappings = new HashSet<CustomerStoreReportMapping>();
            this.DeliveryInfoes = new HashSet<DeliveryInfo>();
            this.MembershipCards = new HashSet<MembershipCard>();
            this.Orders = new HashSet<Order>();
            this.OrderGroups = new HashSet<OrderGroup>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonNumber { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public int Type { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string IDCard { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> StoreRegisterId { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> deliveryInfoDefault { get; set; }
        public string picURL { get; set; }
        public string AccountPhone { get; set; }
        public string FacebookId { get; set; }
        public Nullable<int> PartnerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProductMapping> CustomerProductMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerStoreReportMapping> CustomerStoreReportMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryInfo> DeliveryInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipCard> MembershipCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderGroup> OrderGroups { get; set; }
    }
}
