//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateReport
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string CreateBy { get; set; }
        public int Status { get; set; }
        public int StoreID { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> FinalAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> DiscountOrderDetail { get; set; }
        public Nullable<double> TotalCash { get; set; }
        public int TotalOrder { get; set; }
        public int TotalOrderAtStore { get; set; }
        public int TotalOrderTakeAway { get; set; }
        public int TotalOrderDelivery { get; set; }
        public double TotalOrderDetail { get; set; }
        public double TotalOrderFeeItem { get; set; }
        public int TotalOrderCard { get; set; }
        public Nullable<int> TotalOrderCanceled { get; set; }
        public Nullable<int> TotalOrderPreCanceled { get; set; }
        public Nullable<double> FinalAmountAtStore { get; set; }
        public Nullable<double> FinalAmountTakeAway { get; set; }
        public Nullable<double> FinalAmountDelivery { get; set; }
        public Nullable<double> FinalAmountCard { get; set; }
        public Nullable<double> FinalAmountCanceled { get; set; }
        public Nullable<double> FinalAmountPreCanceled { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
