//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PersonId { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> RentId { get; set; }
        public Nullable<int> RentGroup { get; set; }
        public string Note { get; set; }
    
        public virtual OrderGroup OrderGroup { get; set; }
    }
}
