//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipCardType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MembershipCardType()
        {
            this.MembershipCards = new HashSet<MembershipCard>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string AppendCode { get; set; }
        public int BrandId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<int> TypeLevel { get; set; }
        public Nullable<int> TypePoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipCard> MembershipCards { get; set; }
    }
}
