//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailPromotionMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetailPromotionMapping()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public int OrderDetailId { get; set; }
        public int PromotionId { get; set; }
        public Nullable<int> PromotionDetailId { get; set; }
        public decimal DiscountAmount { get; set; }
        public Nullable<double> DiscountRate { get; set; }
        public bool Active { get; set; }
        public int MappingIndex { get; set; }
        public Nullable<int> TmpMappingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
