//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerMapping
    {
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string Config { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Active { get; set; }
        public int Id { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
