//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySlipItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PaySlipId { get; set; }
        public Nullable<int> PayrollDetailId { get; set; }
        public Nullable<double> Value { get; set; }
        public bool Active { get; set; }
    
        public virtual PayrollDetail PayrollDetail { get; set; }
        public virtual PaySlip PaySlip { get; set; }
    }
}
