//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceGroup()
        {
            this.OrderFeeItems = new HashSet<OrderFeeItem>();
            this.RoomCategoryPriceGroupMappings = new HashSet<RoomCategoryPriceGroupMapping>();
            this.PriceNights = new HashSet<PriceNight>();
        }
    
        public int PriceGroupID { get; set; }
        public string PriceGroupName { get; set; }
        public System.DateTime StartDayTime { get; set; }
        public System.DateTime EndNightTime { get; set; }
        public double DayPrice { get; set; }
        public int RoundMinute { get; set; }
        public double FirstHourPrice { get; set; }
        public double SecondHourPrice { get; set; }
        public double ThirdHourPrice { get; set; }
        public double NextHourPrice { get; set; }
        public int NightAdditionPriceID { get; set; }
        public bool IsAvailable { get; set; }
        public double AdditionPrice { get; set; }
        public int DayLimitTime1 { get; set; }
        public double DayPriceLimitTime1 { get; set; }
        public int DayLimitTime2 { get; set; }
        public double DayPriceLimitTime2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFeeItem> OrderFeeItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomCategoryPriceGroupMapping> RoomCategoryPriceGroupMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceNight> PriceNights { get; set; }
    }
}
