//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceNight
    {
        public int RoomPriceID { get; set; }
        public int PriceGroupID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public double Price { get; set; }
        public int MaxDuration { get; set; }
        public double PricePerHour { get; set; }
        public System.DateTime CheckTime { get; set; }
    
        public virtual PriceGroup PriceGroup { get; set; }
    }
}
