//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CustomerProductMappings = new HashSet<CustomerProductMapping>();
            this.DateProducts = new HashSet<DateProduct>();
            this.Favoriteds = new HashSet<Favorited>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductItemCompositionMappings = new HashSet<ProductItemCompositionMapping>();
            this.ProductComboDetails = new HashSet<ProductComboDetail>();
            this.ProductComboDetails1 = new HashSet<ProductComboDetail>();
            this.ProductCollectionItemMappings = new HashSet<ProductCollectionItemMapping>();
            this.ProductDetailMappings = new HashSet<ProductDetailMapping>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductSpecifications = new HashSet<ProductSpecification>();
            this.RatingProducts = new HashSet<RatingProduct>();
            this.RatingStars = new HashSet<RatingStar>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductNameEng { get; set; }
        public double Price { get; set; }
        public string PicURL { get; set; }
        public int CatID { get; set; }
        public bool IsAvailable { get; set; }
        public string Code { get; set; }
        public double DiscountPercent { get; set; }
        public double DiscountPrice { get; set; }
        public int ProductType { get; set; }
        public int DisplayOrder { get; set; }
        public bool HasExtra { get; set; }
        public bool IsFixedPrice { get; set; }
        public Nullable<int> PosX { get; set; }
        public Nullable<int> PosY { get; set; }
        public Nullable<int> ColorGroup { get; set; }
        public Nullable<int> Group { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<bool> IsMenuDisplay { get; set; }
        public Nullable<int> GeneralProductId { get; set; }
        public string Att1 { get; set; }
        public string Att2 { get; set; }
        public string Att3 { get; set; }
        public string Att4 { get; set; }
        public string Att5 { get; set; }
        public string Att6 { get; set; }
        public string Att7 { get; set; }
        public string Att8 { get; set; }
        public string Att9 { get; set; }
        public string Att10 { get; set; }
        public Nullable<int> MaxExtra { get; set; }
        public string Description { get; set; }
        public string DescriptionEng { get; set; }
        public string Introduction { get; set; }
        public string IntroductionEng { get; set; }
        public Nullable<int> PrintGroup { get; set; }
        public string SeoName { get; set; }
        public Nullable<int> IsHomePage { get; set; }
        public string WebContent { get; set; }
        public string SeoKeyWords { get; set; }
        public string SeoDescription { get; set; }
        public bool Active { get; set; }
        public int IsDefaultChildProduct { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> SaleType { get; set; }
        public bool IsMostOrdered { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> RatingTotal { get; set; }
        public Nullable<int> NumOfUserVoted { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProductMapping> CustomerProductMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DateProduct> DateProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorited> Favoriteds { get; set; }
        public virtual Group Group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductItemCompositionMapping> ProductItemCompositionMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComboDetail> ProductComboDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComboDetail> ProductComboDetails1 { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCollectionItemMapping> ProductCollectionItemMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetailMapping> ProductDetailMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingProduct> RatingProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingStar> RatingStars { get; set; }
    }
}
