//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.CategoryExtraMappings = new HashSet<CategoryExtraMapping>();
            this.CategoryExtraMappings1 = new HashSet<CategoryExtraMapping>();
            this.Products = new HashSet<Product>();
            this.ProductCategory1 = new HashSet<ProductCategory>();
        }
    
        public int CateID { get; set; }
        public string CateName { get; set; }
        public string CateNameEng { get; set; }
        public int Type { get; set; }
        public bool IsDisplayed { get; set; }
        public bool IsDisplayedWebsite { get; set; }
        public bool IsExtra { get; set; }
        public int DisplayOrder { get; set; }
        public string AdjustmentNote { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string SeoName { get; set; }
        public string SeoKeyword { get; set; }
        public string SeoDescription { get; set; }
        public string ImageFontAwsomeCss { get; set; }
        public Nullable<int> ParentCateId { get; set; }
        public Nullable<int> Position { get; set; }
        public bool Active { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string PicUrl { get; set; }
        public string BannerUrl { get; set; }
        public string Description { get; set; }
        public string DescriptionEng { get; set; }
        public string BannerDescription { get; set; }
        public string BannerDescriptionEng { get; set; }
        public string Att1 { get; set; }
        public string Att2 { get; set; }
        public string Att3 { get; set; }
        public string Att4 { get; set; }
        public string Att5 { get; set; }
        public string Att6 { get; set; }
        public string Att7 { get; set; }
        public string Att8 { get; set; }
        public string Att9 { get; set; }
        public string Att10 { get; set; }
        public Nullable<double> VAT { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryExtraMapping> CategoryExtraMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryExtraMapping> CategoryExtraMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ProductCategory1 { get; set; }
        public virtual ProductCategory ProductCategory2 { get; set; }
    }
}
