//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCollection()
        {
            this.ProductCollectionItemMappings = new HashSet<ProductCollectionItemMapping>();
        }
    
        public int Id { get; set; }
        public int StoreId { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public string DescriptionEng { get; set; }
        public string SEO { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
        public string Link { get; set; }
        public string BannerUrl { get; set; }
        public Nullable<int> BrandId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCollectionItemMapping> ProductCollectionItemMappings { get; set; }
    }
}
