//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.OrderDetailPromotionMappings = new HashSet<OrderDetailPromotionMapping>();
            this.OrderPromotionMappings = new HashSet<OrderPromotionMapping>();
            this.PromotionStoreMappings = new HashSet<PromotionStoreMapping>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int PromotionID { get; set; }
        public string PromotionCode { get; set; }
        public string PromotionName { get; set; }
        public string PromotionClassName { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageCss { get; set; }
        public int ApplyLevel { get; set; }
        public int GiftType { get; set; }
        public bool IsForMember { get; set; }
        public bool Active { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> ApplyFromTime { get; set; }
        public Nullable<int> ApplyToTime { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsVoucher { get; set; }
        public Nullable<bool> IsApplyOnce { get; set; }
        public Nullable<int> VoucherQuantity { get; set; }
        public Nullable<int> VoucherUsedQuantity { get; set; }
        public int PromotionType { get; set; }
        public Nullable<int> FromHappyDay { get; set; }
        public Nullable<int> ToHappyDay { get; set; }
        public Nullable<int> FromHoursHappy { get; set; }
        public Nullable<int> ToHoursHappy { get; set; }
        public Nullable<bool> UsingPoint { get; set; }
        public Nullable<int> ApplyToPartner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailPromotionMapping> OrderDetailPromotionMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPromotionMapping> OrderPromotionMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionStoreMapping> PromotionStoreMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
