//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomID { get; set; }
        public string RoomName { get; set; }
        public string RoomDescription { get; set; }
        public int RoomStatus { get; set; }
        public int FloorID { get; set; }
        public int CategoryID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CurrentRentId { get; set; }
        public Nullable<int> RentStatus { get; set; }
        public int PosX { get; set; }
        public int PosSpanX { get; set; }
        public int PosY { get; set; }
        public int PosSpanY { get; set; }
        public Nullable<int> RentType { get; set; }
    
        public virtual RoomCategory RoomCategory { get; set; }
        public virtual RoomFloor RoomFloor { get; set; }
    }
}
