//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomCategoryPriceGroupMapping
    {
        public int CategoryID { get; set; }
        public int PriceGroupID { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual PriceGroup PriceGroup { get; set; }
        public virtual RoomCategory RoomCategory { get; set; }
    }
}
