//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryHour
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Duration { get; set; }
        public int InsertMode { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<int> TimeModeRuleId { get; set; }
        public string ExistCode { get; set; }
        public bool Active { get; set; }
    }
}
