//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWebRouteModel
    {
        public int Id { get; set; }
        public int StoreWebRouteId { get; set; }
        public string Name { get; set; }
        public int ViewModelType { get; set; }
        public string IdRouteValueName { get; set; }
        public string IdRouteDefaultValue { get; set; }
        public bool Active { get; set; }
    
        public virtual StoreWebRoute StoreWebRoute { get; set; }
    }
}
