//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeModeRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeModeRule()
        {
            this.SalaryRules = new HashSet<SalaryRule>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> StartHour { get; set; }
        public Nullable<System.TimeSpan> EndHour { get; set; }
        public Nullable<double> MinDuration { get; set; }
        public Nullable<double> MaxDuration { get; set; }
        public Nullable<int> DayModeId { get; set; }
        public Nullable<int> TimeModeTypeId { get; set; }
        public Nullable<double> DefaultRate { get; set; }
        public int BrandId { get; set; }
        public bool Active { get; set; }
    
        public virtual DayMode DayMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryRule> SalaryRules { get; set; }
        public virtual TimeModeType TimeModeType { get; set; }
    }
}
