//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPage
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string PageContent { get; set; }
        public string PageTitle { get; set; }
        public string MetaDescription { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string SeoName { get; set; }
        public string MetaKeyword { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
