//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promoter.DataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipAccount
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> MembershipId { get; set; }
        public Nullable<double> Balance { get; set; }
    
        public virtual Membership Membership { get; set; }
    }
}
