//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promoter.DataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_DateTimeFilter
    {
        public int FilterId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> BeginHour { get; set; }
        public Nullable<System.TimeSpan> EndHour { get; set; }
        public int ConstraintId { get; set; }
        public bool Active { get; set; }
    
        public virtual PromotionConstraint PromotionConstraint { get; set; }
    }
}
