//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promoter.DataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_ProductFilter
    {
        public int FilterId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductMenuId { get; set; }
        public Nullable<int> MinBuyQuantity { get; set; }
        public Nullable<int> MaxBuyQuantity { get; set; }
        public int ConstraintId { get; set; }
        public bool Active { get; set; }
    
        public virtual PromotionConstraint PromotionConstraint { get; set; }
    }
}
