//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promoter.DataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionAwardDiscount
    {
        public int PromotionAwardId { get; set; }
        public Nullable<int> ForProductId { get; set; }
        public Nullable<int> BuyXGetYAmount { get; set; }
        public Nullable<double> FixedUpsizePrice { get; set; }
        public Nullable<double> SyncPrice { get; set; }
        public Nullable<double> DiscountAmout { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<double> ShipDiscount { get; set; }
        public int PromotionDetailId { get; set; }
        public bool Active { get; set; }
    
        public virtual PromotionDetail PromotionDetail { get; set; }
    }
}
