//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promoter.DataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionConstraint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromotionConstraint()
        {
            this.PC_DateTimeFilter = new HashSet<PC_DateTimeFilter>();
            this.PC_ProductFilter = new HashSet<PC_ProductFilter>();
            this.PC_StoreFilter = new HashSet<PC_StoreFilter>();
        }
    
        public int ConstraintId { get; set; }
        public bool HasTimeContraint { get; set; }
        public Nullable<System.DateTime> PromotionBeginDate { get; set; }
        public Nullable<System.DateTime> PromotionEndDate { get; set; }
        public bool HasOrderConstraint { get; set; }
        public Nullable<bool> FixProductFilter { get; set; }
        public Nullable<int> MinTotalProducts { get; set; }
        public Nullable<int> MaxTotalProducts { get; set; }
        public Nullable<double> MinTotalAmount { get; set; }
        public Nullable<double> MaxTotalAmount { get; set; }
        public Nullable<int> MinPersonCount { get; set; }
        public Nullable<int> MaxPersonCount { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public bool HasPaymentConstraint { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string PaymentPartnerCode { get; set; }
        public bool HasStoreConstraint { get; set; }
        public bool HasMembershipConstraint { get; set; }
        public string MembershipCode { get; set; }
        public string MembershipTypeCode { get; set; }
        public string MembershipCodePattern { get; set; }
        public Nullable<int> MembershipMinLevel { get; set; }
        public Nullable<int> MembershipMaxLevel { get; set; }
        public Nullable<double> MinPoint { get; set; }
        public Nullable<double> MaxPoint { get; set; }
        public Nullable<int> MinJoinDate { get; set; }
        public bool HasSaleModeConstraint { get; set; }
        public Nullable<bool> ForTakeAway { get; set; }
        public Nullable<bool> ForDelivery { get; set; }
        public Nullable<bool> ForInstore { get; set; }
        public Nullable<bool> ForInstorePreorder { get; set; }
        public bool HasCollectionConstraint { get; set; }
        public Nullable<int> PromotionDetailId { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_DateTimeFilter> PC_DateTimeFilter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_ProductFilter> PC_ProductFilter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_StoreFilter> PC_StoreFilter { get; set; }
        public virtual PromotionDetail PromotionDetail { get; set; }
    }
}
