//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promoter.DataService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromoterEntities : DbContext
    {
        public PromoterEntities()
            : base("name=PromoterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PC_DateTimeFilter> PC_DateTimeFilter { get; set; }
        public virtual DbSet<PC_ProductFilter> PC_ProductFilter { get; set; }
        public virtual DbSet<PC_StoreFilter> PC_StoreFilter { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PromotionAwardCashback> PromotionAwardCashbacks { get; set; }
        public virtual DbSet<PromotionAwardDiscount> PromotionAwardDiscounts { get; set; }
        public virtual DbSet<PromotionAwardGift> PromotionAwardGifts { get; set; }
        public virtual DbSet<PromotionConstraint> PromotionConstraints { get; set; }
        public virtual DbSet<PromotionDetail> PromotionDetails { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
    }
}
