//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promoter.DataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionAwardGift
    {
        public int PromotionAwardId { get; set; }
        public Nullable<int> ForProductId { get; set; }
        public Nullable<int> GiftVoucherId { get; set; }
        public Nullable<int> GiftVoucherOfPromotionId { get; set; }
        public Nullable<int> GiftPresentId { get; set; }
        public Nullable<int> GiftProductId { get; set; }
        public int PromotionDetailId { get; set; }
        public bool Active { get; set; }
    
        public virtual PromotionDetail PromotionDetail { get; set; }
    }
}
