//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promoter.DataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int VoucherId { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public int ApplyQuantity { get; set; }
        public int AppliedQuantity { get; set; }
        public bool IsGetted { get; set; }
        public string MembershipCode { get; set; }
        public int PromotionDetailId { get; set; }
        public bool Active { get; set; }
    
        public virtual PromotionDetail PromotionDetail { get; set; }
    }
}
