//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int OfUserId { get; set; }
        public int ToPostId { get; set; }
        public string TextContent { get; set; }
        public Nullable<System.DateTime> PostedTime { get; set; }
        public bool Active { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Post Post { get; set; }
    }
}
