//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAction
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public string CustomerCode { get; set; }
        public string BrandCode { get; set; }
        public string Detail_LetterCode { get; set; }
        public string Detail_LetterContent { get; set; }
        public string Detail_ToCustomerCode { get; set; }
        public string Detail_ToPhoneNumber { get; set; }
        public string Detail_ToEmail { get; set; }
    }
}
