//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppEntity : DbContext
    {
        public AppEntity()
            : base("name=AppEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppAction> AppActions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerEvent> CustomerEvents { get; set; }
        public virtual DbSet<CustomerFilter> CustomerFilters { get; set; }
        public virtual DbSet<CustomerFilterMetadata> CustomerFilterMetadatas { get; set; }
        public virtual DbSet<CustomerMetadata> CustomerMetadatas { get; set; }
        public virtual DbSet<EventTrigger> EventTriggers { get; set; }
    }
}
