//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.Interactives = new HashSet<Interactive>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ToPostId { get; set; }
        public Nullable<int> ToAnswerId { get; set; }
        public string TextContent { get; set; }
        public Nullable<System.DateTime> PostedTime { get; set; }
        public Nullable<int> OfUserId { get; set; }
        public bool Active { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interactive> Interactives { get; set; }
    }
}
