//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFilterMetadata
    {
        public int FilterID { get; set; }
        public string MetadataKey { get; set; }
        public string Value { get; set; }
        public bool Active { get; set; }
    
        public virtual CustomerFilter CustomerFilter { get; set; }
    }
}
