//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTrigger
    {
        public int ID { get; set; }
        public string BrandCode { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Action_SmsEnable { get; set; }
        public Nullable<bool> Action_EmailEnable { get; set; }
        public string Action_LetterCode { get; set; }
        public string Action_LetterContent { get; set; }
        public string Action_Placeholder { get; set; }
        public string Event_OnEnterFilterCode { get; set; }
        public string Event_OnLeaveFilterCode { get; set; }
        public string Event_OnSmsCodeConfirmed { get; set; }
        public string Event_OnEmailCodeConfirmed { get; set; }
    }
}
