//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsOfPost
    {
        public int PostId { get; set; }
        public int TagId { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
