
// Generated helper templates
// Generated items
// TNT.Template.DataService\DataServiceTest\ViewModels\CustomerFeedbackViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\WebPageViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\WebMenuCategoryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\WebMenuViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\WebElementTypeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\WebElementViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\WebCustomerFeedbackViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\WardViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\VoucherViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ViewCounterViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\VATOrderMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\VATOrderViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\UserViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TransactionViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TokenUserViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TimeModeTypeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TimeModeRuleViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TimeFrameViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ThemeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TemplateRuleMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TemplateReportProductItemMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TemplateDetailMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TagMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\TagViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\SystemPartnerMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\sysdiagramViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\SubRentGroupViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreWebViewCounterViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreWebSettingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreWebRouteModelViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreWebRouteViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreUserViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreThemeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreGroupMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreGroupViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreDomainViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\StoreViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\SalaryRuleViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\SalaryHourViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\RoomFloorViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\RoomCategoryPriceGroupMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\RoomCategoryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\RoomViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\RoleViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ReportTrackingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\RatingStarViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\RatingProductViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProvinceViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProviderProductItemMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProviderViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PromotionStoreMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PromotionDetailViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PromotionViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProfileViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductSpecificationViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductItemCompositionMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductItemCategoryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductImageCollectionItemMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductImageCollectionViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductImageViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductDetailMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductComboDetailViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductCollectionItemMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductCollectionViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductCategoryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ProductViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PriceNightViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PriceGroupViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PriceAdditionViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PosFileViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PosConfigViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PosViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PaySlipTemplateViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PaySlipItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PayslipAttributeMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PayslipAttributeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PaySlipViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PayrollPeriodViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PayrollDetailViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PayrollCategoryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PaymentReportViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PaymentPartnerViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PaymentViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PartnerMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\PartnerViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\OrderPromotionMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\OrderGroupViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\OrderFeeItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\OrderDetailPromotionMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\OrderDetailViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\OrderViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\NotificationViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\MenuViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\MembershipCardTypeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\MembershipCardViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\MachineConnectViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\LanguageValueViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\LanguageKeyViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\LanguageViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\InventoryTemplateReportViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\InventoryReceiptItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\InventoryReceiptViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\InventoryDateReportItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\InventoryDateReportViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\InventoryCheckingItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\InventoryCheckingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ImageCollectionItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ImageCollectionViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\GuestViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\GroupViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\FingerScanMachineViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\FavoritedViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\EventLocationViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\EmployeeInStoreViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\EmployeeGroupViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\EmployeeFingerViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\EmployeeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DistrictViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DeviceViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DeliveryInformationViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DeliveryInfoViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DayModeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DateReportViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DateProductItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DateProductViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\DateHotelReportViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CustomerTypeViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CustomerStoreReportMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CustomerProductMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CustomerFilterViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CustomerViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CouponProviderViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CouponCampaignViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CouponViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CostInventoryMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CostCategoryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CostViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ContactViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CheckFingerViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CategoryExtraMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\CategoryExtraViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\BrandViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\BlogPostImageViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\BlogPostCollectionItemMappingViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\BlogPostCollectionItemViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\BlogPostCollectionViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\BlogPostViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\BlogCategoryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\AttendanceDateViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\AttendanceViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\AspNetUserViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\AspNetUserLoginViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\AspNetUserClaimViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\AspNetRoleViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ArticleViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\AreaDeliveryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\ApplicationViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\AccountViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\C__MigrationHistoryViewModel.cs
// TNT.Template.DataService\DataServiceTest\ViewModels\BaseViewModelGen.cs
