
// Generated helper templates
// Generated items
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CustomerFeedbackService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\WebPageService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\WebMenuCategoryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\WebMenuService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\WebElementTypeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\WebElementService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\WebCustomerFeedbackService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\WardService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\VoucherService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ViewCounterService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\VATOrderMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\VATOrderService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\UserService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TransactionService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TokenUserService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TimeModeTypeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TimeModeRuleService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TimeFrameService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ThemeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TemplateRuleMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TemplateReportProductItemMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TemplateDetailMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TagMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\TagService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\SystemPartnerMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\sysdiagramService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\SubRentGroupService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreWebViewCounterService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreWebSettingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreWebRouteModelService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreWebRouteService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreUserService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreThemeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreGroupMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreGroupService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreDomainService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\StoreService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\SalaryRuleService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\SalaryHourService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\RoomFloorService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\RoomCategoryPriceGroupMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\RoomCategoryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\RoomService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\RoleService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ReportTrackingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\RatingStarService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\RatingProductService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProvinceService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProviderProductItemMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProviderService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PromotionStoreMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PromotionDetailService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PromotionService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProfileService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductSpecificationService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductItemCompositionMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductItemCategoryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductImageCollectionItemMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductImageCollectionService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductImageService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductDetailMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductComboDetailService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductCollectionItemMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductCollectionService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductCategoryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ProductService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PriceNightService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PriceGroupService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PriceAdditionService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PosFileService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PosConfigService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PosService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PaySlipTemplateService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PaySlipItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PayslipAttributeMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PayslipAttributeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PaySlipService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PayrollPeriodService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PayrollDetailService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PayrollCategoryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PaymentReportService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PaymentPartnerService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PaymentService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PartnerMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\PartnerService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\OrderPromotionMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\OrderGroupService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\OrderFeeItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\OrderDetailPromotionMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\OrderDetailService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\OrderService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\NotificationService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\MenuService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\MembershipCardTypeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\MembershipCardService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\MachineConnectService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\LanguageValueService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\LanguageKeyService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\LanguageService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\InventoryTemplateReportService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\InventoryReceiptItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\InventoryReceiptService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\InventoryDateReportItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\InventoryDateReportService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\InventoryCheckingItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\InventoryCheckingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ImageCollectionItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ImageCollectionService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\GuestService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\GroupService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\FingerScanMachineService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\FavoritedService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\EventLocationService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\EmployeeInStoreService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\EmployeeGroupService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\EmployeeFingerService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\EmployeeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DistrictService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DeviceService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DeliveryInformationService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DeliveryInfoService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DayModeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DateReportService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DateProductItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DateProductService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\DateHotelReportService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CustomerTypeService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CustomerStoreReportMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CustomerProductMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CustomerFilterService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CustomerService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CouponProviderService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CouponCampaignService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CouponService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CostInventoryMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CostCategoryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CostService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ContactService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CheckFingerService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CategoryExtraMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\CategoryExtraService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\BrandService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\BlogPostImageService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\BlogPostCollectionItemMappingService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\BlogPostCollectionItemService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\BlogPostCollectionService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\BlogPostService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\BlogCategoryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\AttendanceDateService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\AttendanceService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\AspNetUserService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\AspNetUserLoginService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\AspNetUserClaimService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\AspNetRoleService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ArticleService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\AreaDeliveryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\ApplicationService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\AccountService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\C__MigrationHistoryService.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Services\BaseService.cs
