
// Generated helper templates
// Generated items
// TNT.Template.DataService\DataServiceTest\Models\Services\CustomerFeedbackServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\WebPageServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\WebMenuCategoryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\WebMenuServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\WebElementTypeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\WebElementServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\WebCustomerFeedbackServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\WardServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\VoucherServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ViewCounterServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\VATOrderMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\VATOrderServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\UserServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TransactionServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TokenUserServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TimeModeTypeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TimeModeRuleServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TimeFrameServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ThemeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TemplateRuleMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TemplateReportProductItemMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TemplateDetailMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TagMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\TagServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\SystemPartnerMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\sysdiagramServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\SubRentGroupServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreWebViewCounterServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreWebSettingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreWebRouteModelServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreWebRouteServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreUserServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreThemeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreGroupMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreGroupServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreDomainServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\StoreServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\SalaryRuleServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\SalaryHourServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\RoomFloorServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\RoomCategoryPriceGroupMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\RoomCategoryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\RoomServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\RoleServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ReportTrackingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\RatingStarServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\RatingProductServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProvinceServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProviderProductItemMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProviderServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PromotionStoreMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PromotionDetailServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PromotionServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProfileServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductSpecificationServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductItemCompositionMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductItemCategoryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductImageCollectionItemMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductImageCollectionServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductImageServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductDetailMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductComboDetailServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductCollectionItemMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductCollectionServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductCategoryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ProductServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PriceNightServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PriceGroupServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PriceAdditionServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PosFileServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PosConfigServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PosServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PaySlipTemplateServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PaySlipItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PayslipAttributeMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PayslipAttributeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PaySlipServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PayrollPeriodServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PayrollDetailServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PayrollCategoryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PaymentReportServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PaymentPartnerServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PaymentServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PartnerMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\PartnerServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\OrderPromotionMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\OrderGroupServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\OrderFeeItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\OrderDetailPromotionMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\OrderDetailServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\OrderServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\NotificationServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\MenuServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\MembershipCardTypeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\MembershipCardServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\MachineConnectServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\LanguageValueServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\LanguageKeyServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\LanguageServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\InventoryTemplateReportServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\InventoryReceiptItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\InventoryReceiptServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\InventoryDateReportItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\InventoryDateReportServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\InventoryCheckingItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\InventoryCheckingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ImageCollectionItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ImageCollectionServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\GuestServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\GroupServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\FingerScanMachineServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\FavoritedServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\EventLocationServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\EmployeeInStoreServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\EmployeeGroupServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\EmployeeFingerServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\EmployeeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DistrictServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DeviceServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DeliveryInformationServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DeliveryInfoServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DayModeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DateReportServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DateProductItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DateProductServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\DateHotelReportServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CustomerTypeServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CustomerStoreReportMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CustomerProductMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CustomerFilterServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CustomerServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CouponProviderServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CouponCampaignServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CouponServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CostInventoryMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CostCategoryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CostServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ContactServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CheckFingerServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CategoryExtraMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\CategoryExtraServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\BrandServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\BlogPostImageServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\BlogPostCollectionItemMappingServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\BlogPostCollectionItemServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\BlogPostCollectionServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\BlogPostServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\BlogCategoryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\AttendanceDateServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\AttendanceServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\AspNetUserServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\AspNetUserLoginServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\AspNetUserClaimServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\AspNetRoleServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ArticleServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\AreaDeliveryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\ApplicationServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\AccountServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\C__MigrationHistoryServiceGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Services\BaseServiceGen.cs
