
// Generated helper templates
// Generated items
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CustomerFeedbackExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\WebPageExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\WebMenuCategoryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\WebMenuExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\WebElementTypeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\WebElementExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\WebCustomerFeedbackExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\WardExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\VoucherExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ViewCounterExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\VATOrderMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\VATOrderExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\UserExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TransactionExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TokenUserExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TimeModeTypeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TimeModeRuleExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TimeFrameExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ThemeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TemplateRuleMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TemplateReportProductItemMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TemplateDetailMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TagMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\TagExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\SystemPartnerMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\sysdiagramExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\SubRentGroupExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreWebViewCounterExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreWebSettingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreWebRouteModelExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreWebRouteExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreUserExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreThemeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreGroupMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreGroupExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreDomainExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\StoreExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\SalaryRuleExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\SalaryHourExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\RoomFloorExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\RoomCategoryPriceGroupMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\RoomCategoryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\RoomExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\RoleExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ReportTrackingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\RatingStarExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\RatingProductExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProvinceExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProviderProductItemMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProviderExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PromotionStoreMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PromotionDetailExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PromotionExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProfileExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductSpecificationExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductItemCompositionMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductItemCategoryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductImageCollectionItemMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductImageCollectionExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductImageExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductDetailMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductComboDetailExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductCollectionItemMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductCollectionExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductCategoryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ProductExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PriceNightExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PriceGroupExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PriceAdditionExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PosFileExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PosConfigExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PosExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PaySlipTemplateExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PaySlipItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PayslipAttributeMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PayslipAttributeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PaySlipExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PayrollPeriodExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PayrollDetailExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PayrollCategoryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PaymentReportExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PaymentPartnerExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PaymentExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PartnerMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\PartnerExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\OrderPromotionMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\OrderGroupExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\OrderFeeItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\OrderDetailPromotionMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\OrderDetailExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\OrderExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\NotificationExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\MenuExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\MembershipCardTypeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\MembershipCardExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\MachineConnectExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\LanguageValueExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\LanguageKeyExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\LanguageExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\InventoryTemplateReportExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\InventoryReceiptItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\InventoryReceiptExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\InventoryDateReportItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\InventoryDateReportExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\InventoryCheckingItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\InventoryCheckingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ImageCollectionItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ImageCollectionExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\GuestExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\GroupExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\FingerScanMachineExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\FavoritedExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\EventLocationExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\EmployeeInStoreExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\EmployeeGroupExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\EmployeeFingerExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\EmployeeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DistrictExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DeviceExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DeliveryInformationExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DeliveryInfoExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DayModeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DateReportExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DateProductItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DateProductExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\DateHotelReportExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CustomerTypeExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CustomerStoreReportMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CustomerProductMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CustomerFilterExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CustomerExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CouponProviderExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CouponCampaignExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CouponExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CostInventoryMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CostCategoryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CostExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ContactExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CheckFingerExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CategoryExtraMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\CategoryExtraExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\BrandExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\BlogPostImageExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\BlogPostCollectionItemMappingExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\BlogPostCollectionItemExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\BlogPostCollectionExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\BlogPostExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\BlogCategoryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\AttendanceDateExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\AttendanceExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\AspNetUserExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\AspNetUserLoginExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\AspNetUserClaimExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\AspNetRoleExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ArticleExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\AreaDeliveryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\ApplicationExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\AccountExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Extension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\C__MigrationHistoryExtension.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Extensions\Entity.cs
