//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T2CDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public Nullable<int> InPostId { get; set; }
        public bool Deactive { get; set; }
        public Nullable<int> ByUserId { get; set; }
        public Nullable<System.DateTime> PostedTime { get; set; }
        public string CContent { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
