
// Generated helper templates
// Generated items
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CustomerFeedbackDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\WebPageDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\WebMenuCategoryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\WebMenuDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\WebElementTypeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\WebElementDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\WebCustomerFeedbackDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\WardDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\VoucherDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ViewCounterDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\VATOrderMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\VATOrderDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\UserDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TransactionDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TokenUserDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TimeModeTypeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TimeModeRuleDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TimeFrameDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ThemeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TemplateRuleMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TemplateReportProductItemMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TemplateDetailMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TagMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\TagDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\SystemPartnerMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\sysdiagramDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\SubRentGroupDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreWebViewCounterDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreWebSettingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreWebRouteModelDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreWebRouteDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreUserDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreThemeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreGroupMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreGroupDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreDomainDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\StoreDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\SalaryRuleDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\SalaryHourDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\RoomFloorDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\RoomCategoryPriceGroupMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\RoomCategoryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\RoomDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\RoleDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ReportTrackingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\RatingStarDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\RatingProductDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProvinceDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProviderProductItemMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProviderDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PromotionStoreMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PromotionDetailDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PromotionDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProfileDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductSpecificationDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductItemCompositionMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductItemCategoryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductImageCollectionItemMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductImageCollectionDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductImageDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductDetailMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductComboDetailDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductCollectionItemMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductCollectionDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductCategoryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ProductDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PriceNightDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PriceGroupDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PriceAdditionDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PosFileDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PosConfigDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PosDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PaySlipTemplateDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PaySlipItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PayslipAttributeMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PayslipAttributeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PaySlipDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PayrollPeriodDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PayrollDetailDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PayrollCategoryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PaymentReportDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PaymentPartnerDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PaymentDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PartnerMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\PartnerDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\OrderPromotionMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\OrderGroupDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\OrderFeeItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\OrderDetailPromotionMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\OrderDetailDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\OrderDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\NotificationDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\MenuDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\MembershipCardTypeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\MembershipCardDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\MachineConnectDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\LanguageValueDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\LanguageKeyDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\LanguageDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\InventoryTemplateReportDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\InventoryReceiptItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\InventoryReceiptDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\InventoryDateReportItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\InventoryDateReportDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\InventoryCheckingItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\InventoryCheckingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ImageCollectionItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ImageCollectionDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\GuestDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\GroupDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\FingerScanMachineDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\FavoritedDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\EventLocationDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\EmployeeInStoreDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\EmployeeGroupDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\EmployeeFingerDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\EmployeeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DistrictDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DeviceDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DeliveryInformationDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DeliveryInfoDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DayModeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DateReportDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DateProductItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DateProductDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\DateHotelReportDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CustomerTypeDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CustomerStoreReportMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CustomerProductMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CustomerFilterDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CustomerDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CouponProviderDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CouponCampaignDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CouponDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CostInventoryMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CostCategoryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CostDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ContactDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CheckFingerDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CategoryExtraMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\CategoryExtraDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\BrandDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\BlogPostImageDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\BlogPostCollectionItemMappingDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\BlogPostCollectionItemDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\BlogPostCollectionDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\BlogPostDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\BlogCategoryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\AttendanceDateDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\AttendanceDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\AspNetUserDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\AspNetUserLoginDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\AspNetUserClaimDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\AspNetRoleDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ArticleDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\AreaDeliveryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\ApplicationDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\AccountDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Domain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\C__MigrationHistoryDomain.cs
// TNT.DataServiceTemplate\DataServiceTest\Models\Domains\BaseDomain.cs
