
// Generated helper templates
// Generated items
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CustomerFeedbackRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\WebPageRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\WebMenuCategoryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\WebMenuRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\WebElementTypeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\WebElementRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\WebCustomerFeedbackRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\WardRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\VoucherRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ViewCounterRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\VATOrderMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\VATOrderRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\UserRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TransactionRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TokenUserRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TimeModeTypeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TimeModeRuleRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TimeFrameRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ThemeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TemplateRuleMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TemplateReportProductItemMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TemplateDetailMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TagMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\TagRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\SystemPartnerMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\sysdiagramRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\SubRentGroupRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreWebViewCounterRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreWebSettingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreWebRouteModelRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreWebRouteRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreUserRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreThemeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreGroupMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreGroupRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreDomainRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\StoreRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\SalaryRuleRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\SalaryHourRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\RoomFloorRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\RoomCategoryPriceGroupMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\RoomCategoryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\RoomRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\RoleRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ReportTrackingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\RatingStarRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\RatingProductRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProvinceRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProviderProductItemMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProviderRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PromotionStoreMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PromotionDetailRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PromotionRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProfileRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductSpecificationRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductItemCompositionMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductItemCategoryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductImageCollectionItemMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductImageCollectionRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductImageRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductDetailMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductComboDetailRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductCollectionItemMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductCollectionRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductCategoryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ProductRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PriceNightRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PriceGroupRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PriceAdditionRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PosFileRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PosConfigRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PosRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PaySlipTemplateRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PaySlipItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PayslipAttributeMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PayslipAttributeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PaySlipRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PayrollPeriodRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PayrollDetailRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PayrollCategoryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PaymentReportRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PaymentPartnerRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PaymentRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PartnerMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\PartnerRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\OrderPromotionMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\OrderGroupRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\OrderFeeItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\OrderDetailPromotionMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\OrderDetailRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\OrderRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\NotificationRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\MenuRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\MembershipCardTypeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\MembershipCardRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\MachineConnectRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\LanguageValueRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\LanguageKeyRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\LanguageRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\InventoryTemplateReportRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\InventoryReceiptItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\InventoryReceiptRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\InventoryDateReportItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\InventoryDateReportRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\InventoryCheckingItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\InventoryCheckingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ImageCollectionItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ImageCollectionRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\GuestRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\GroupRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\FingerScanMachineRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\FavoritedRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\EventLocationRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\EmployeeInStoreRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\EmployeeGroupRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\EmployeeFingerRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\EmployeeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DistrictRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DeviceRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DeliveryInformationRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DeliveryInfoRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DayModeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DateReportRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DateProductItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DateProductRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\DateHotelReportRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CustomerTypeRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CustomerStoreReportMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CustomerProductMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CustomerFilterRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CustomerRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CouponProviderRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CouponCampaignRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CouponRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CostInventoryMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CostCategoryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CostRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ContactRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CheckFingerRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CategoryExtraMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\CategoryExtraRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\BrandRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\BlogPostImageRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\BlogPostCollectionItemMappingRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\BlogPostCollectionItemRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\BlogPostCollectionRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\BlogPostRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\BlogCategoryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\AttendanceDateRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\AttendanceRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\AspNetUserRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\AspNetUserLoginRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\AspNetUserClaimRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\AspNetRoleRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ArticleRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\AreaDeliveryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\ApplicationRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\AccountRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4RepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\C__MigrationHistoryRepositoryGen.cs
// TNT.Template.DataService\DataServiceTest\Models\Repositories\BaseRepositoryGen.cs
