//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ID { get; set; }
        public int StoreId { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }
        public string ContentHTML { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsAvailable { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
