//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostCollectionItem
    {
        public int Id { get; set; }
        public int BlogPostCollectionId { get; set; }
        public int BlogPostId { get; set; }
        public int Position { get; set; }
        public bool Active { get; set; }
    
        public virtual BlogPostCollection BlogPostCollection { get; set; }
    }
}
