//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cost()
        {
            this.CostInventoryMappings = new HashSet<CostInventoryMapping>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int CostID { get; set; }
        public int CatID { get; set; }
        public string CostDescription { get; set; }
        public System.DateTime CostDate { get; set; }
        public double Amount { get; set; }
        public int CostStatus { get; set; }
        public string PaidPerson { get; set; }
        public string LoggedPerson { get; set; }
        public string ApprovedPerson { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> CostCategoryType { get; set; }
        public string CostCode { get; set; }
        public Nullable<int> CostType { get; set; }
    
        public virtual CostCategory CostCategory { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostInventoryMapping> CostInventoryMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
