//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFilter
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CusTypeID { get; set; }
        public Nullable<int> AgeFrom { get; set; }
        public Nullable<int> AgeTo { get; set; }
        public Nullable<int> BirthdayMonth { get; set; }
        public Nullable<System.DateTime> BirthdayFrom { get; set; }
        public Nullable<System.DateTime> BirthdayTo { get; set; }
        public Nullable<int> BirthdayOption { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> VisitedTimesFrom { get; set; }
        public Nullable<int> VisitedTimesTo { get; set; }
        public Nullable<bool> IsEnableCusType { get; set; }
        public Nullable<bool> IsEnableAge { get; set; }
        public Nullable<bool> IsEnableBirthday { get; set; }
        public Nullable<bool> IsEnableGender { get; set; }
        public Nullable<bool> IsEnableVisitedTimes { get; set; }
        public bool Active { get; set; }
        public Nullable<int> BrandId { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
