//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateProduct
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int ProductId { get; set; }
        public int StoreID { get; set; }
        public int Quantity { get; set; }
        public double TotalAmount { get; set; }
        public double Discount { get; set; }
        public double FinalAmount { get; set; }
        public Nullable<int> CategoryId_ { get; set; }
        public string ProductName_ { get; set; }
        public Nullable<int> Time0Quantity { get; set; }
        public Nullable<int> Time1Quantity { get; set; }
        public Nullable<int> Time2Quantity { get; set; }
        public Nullable<int> Time3Quantity { get; set; }
        public Nullable<int> Time4Quantity { get; set; }
        public Nullable<int> Time5Quantity { get; set; }
        public Nullable<int> Time6Quantity { get; set; }
        public Nullable<int> Time7Quantity { get; set; }
        public Nullable<int> Time8Quantity { get; set; }
        public Nullable<int> Time9Quantity { get; set; }
        public Nullable<int> Time10Quantity { get; set; }
        public Nullable<int> Time11Quantity { get; set; }
        public Nullable<int> Time12Quantity { get; set; }
        public Nullable<int> Time13Quantity { get; set; }
        public Nullable<int> Time14Quantity { get; set; }
        public Nullable<int> Time15Quantity { get; set; }
        public Nullable<int> Time16Quantity { get; set; }
        public Nullable<int> Time17Quantity { get; set; }
        public Nullable<int> Time18Quantity { get; set; }
        public Nullable<int> Time19Quantity { get; set; }
        public Nullable<int> Time20Quantity { get; set; }
        public Nullable<int> Time21Quantity { get; set; }
        public Nullable<int> Time22Quantity { get; set; }
        public Nullable<int> Time23Quantity { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<int> QuantityAtStore { get; set; }
        public Nullable<int> QuantityTakeAway { get; set; }
        public Nullable<int> QuantityDelivery { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
