//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Attendances = new HashSet<Attendance>();
            this.CheckFingers = new HashSet<CheckFinger>();
            this.EmployeeFingers = new HashSet<EmployeeFinger>();
            this.EmployeeInStores = new HashSet<EmployeeInStore>();
            this.PaySlips = new HashSet<PaySlip>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Role { get; set; }
        public string EmpEnrollNumber { get; set; }
        public int MainStoreId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public bool Active { get; set; }
        public int BrandId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateStartWork { get; set; }
        public Nullable<int> EmployeeGroupId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeRegency { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> EmployeeSex { get; set; }
        public string PersonalCardId { get; set; }
        public Nullable<System.DateTime> DatePersonalCard { get; set; }
        public string PlaceOfPersonalCard { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string MainAddress { get; set; }
        public string EmployeeHometown { get; set; }
        public string EmployeePlaceBorn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckFinger> CheckFingers { get; set; }
        public virtual EmployeeGroup EmployeeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFinger> EmployeeFingers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeInStore> EmployeeInStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaySlip> PaySlips { get; set; }
    }
}
