//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineConnect
    {
        public int ID { get; set; }
        public int MachineID { get; set; }
        public Nullable<System.DateTime> ConnectTime { get; set; }
        public Nullable<bool> ConnectResult { get; set; }
        public int StoreID { get; set; }
        public int BrandID { get; set; }
        public bool Active { get; set; }
        public string MachineName { get; set; }
        public string MachineCode { get; set; }
    }
}
