//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFeeItem
    {
        public int OrderId { get; set; }
        public int RentId { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> FinalAmount { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string DetailDescription { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public bool IsAddition { get; set; }
        public Nullable<int> ProductType { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> RentMode { get; set; }
        public Nullable<int> PriceGroupId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PriceGroup PriceGroup { get; set; }
    }
}
