//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReport
    {
        public int ID { get; set; }
        public string CreateBy { get; set; }
        public int Status { get; set; }
        public System.DateTime Date { get; set; }
        public int StoreID { get; set; }
        public double CashAmount { get; set; }
        public double MemberCardAmount { get; set; }
        public double BankAmount { get; set; }
        public double VoucherAmount { get; set; }
        public double DebtAmount { get; set; }
        public double OtherAmount { get; set; }
        public double PayDebtAmount { get; set; }
        public double ReceiptAmount { get; set; }
        public double SpendAmount { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
