//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayrollDetail()
        {
            this.PaySlipItems = new HashSet<PaySlipItem>();
            this.TemplateDetailMappings = new HashSet<TemplateDetailMapping>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> PayrollCategoryId { get; set; }
        public bool Active { get; set; }
        public int BrandId { get; set; }
    
        public virtual PayrollCategory PayrollCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaySlipItem> PaySlipItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDetailMapping> TemplateDetailMappings { get; set; }
    }
}
