//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayslipAttributeMapping
    {
        public int Id { get; set; }
        public Nullable<int> PayslipId { get; set; }
        public Nullable<int> AttributeId { get; set; }
        public Nullable<int> Value { get; set; }
        public bool Active { get; set; }
    
        public virtual PaySlip PaySlip { get; set; }
        public virtual PayslipAttribute PayslipAttribute { get; set; }
    }
}
