//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceAddition
    {
        public int AdditionPriceID { get; set; }
        public string EarlyHourRange { get; set; }
        public string EarlyPriceRange { get; set; }
        public string LateHourRange { get; set; }
        public string LatePriceRange { get; set; }
        public string Name { get; set; }
    }
}
