//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImageCollectionItemMapping
    {
        public int Id { get; set; }
        public int ImageCollectionId { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public bool Active { get; set; }
        public int Position { get; set; }
    
        public virtual ProductImageCollection ProductImageCollection { get; set; }
    }
}
