//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductItem()
        {
            this.InventoryDateReportItems = new HashSet<InventoryDateReportItem>();
            this.InventoryReceiptItems = new HashSet<InventoryReceiptItem>();
            this.ProductItemCompositionMappings = new HashSet<ProductItemCompositionMapping>();
            this.ProviderProductItemMappings = new HashSet<ProviderProductItemMapping>();
            this.TemplateReportProductItemMappings = new HashSet<TemplateReportProductItemMapping>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<double> Price { get; set; }
        public string Unit2 { get; set; }
        public Nullable<double> UnitRate { get; set; }
        public Nullable<int> IndexPriority { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string ItemCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryDateReportItem> InventoryDateReportItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryReceiptItem> InventoryReceiptItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductItemCompositionMapping> ProductItemCompositionMappings { get; set; }
        public virtual ProductItemCategory ProductItemCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderProductItemMapping> ProviderProductItemMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateReportProductItemMapping> TemplateReportProductItemMappings { get; set; }
    }
}
