//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderProductItemMapping
    {
        public int ProviderProductItemId { get; set; }
        public int ProviderID { get; set; }
        public int ProductItemID { get; set; }
        public bool Active { get; set; }
    
        public virtual ProductItem ProductItem { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
