//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWebViewCounter
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int WeeklyViewCount { get; set; }
        public int MonthlyViewCount { get; set; }
        public int TotalViewCount { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int TodayViewCount { get; set; }
        public int YearlyViewCount { get; set; }
        public bool Active { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
