//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRentGroup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int RoomType { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ServicedQuantity { get; set; }
        public int RentGroupID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SourceId { get; set; }
    
        public virtual OrderGroup OrderGroup { get; set; }
        public virtual RoomCategory RoomCategory { get; set; }
    }
}
