//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagMapping
    {
        public int Id { get; set; }
        public int TagId { get; set; }
        public int CategoryId { get; set; }
        public int TagBlogId { get; set; }
    
        public virtual BlogCategory BlogCategory { get; set; }
        public virtual BlogPost BlogPost { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
