//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateRuleMapping
    {
        public int Id { get; set; }
        public Nullable<int> PaySlipTemplateId { get; set; }
        public Nullable<int> SalaryRuleId { get; set; }
        public bool Active { get; set; }
    
        public virtual PaySlipTemplate PaySlipTemplate { get; set; }
        public virtual SalaryRule SalaryRule { get; set; }
    }
}
