//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateReportProductItemMapping
    {
        public int Id { get; set; }
        public int InventoryTemplateReportId { get; set; }
        public int ProductItemId { get; set; }
        public int MappingIndex { get; set; }
    
        public virtual InventoryTemplateReport InventoryTemplateReport { get; set; }
        public virtual ProductItem ProductItem { get; set; }
    }
}
