//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeFrame
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.TimeSpan Duration { get; set; }
        public int BrandId { get; set; }
        public Nullable<int> EmployeeGroupId { get; set; }
        public bool Active { get; set; }
        public System.TimeSpan BreakTime { get; set; }
        public Nullable<bool> IsOverTime { get; set; }
        public int InMode { get; set; }
        public int OutMode { get; set; }
        public int BreakCount { get; set; }
        public Nullable<System.TimeSpan> CheckInExpandTime { get; set; }
        public Nullable<System.TimeSpan> CheckOutExpandTime { get; set; }
        public Nullable<int> StoreFilter { get; set; }
        public Nullable<System.TimeSpan> ComeLateExpandTime { get; set; }
        public Nullable<System.TimeSpan> LeaveEarlyExpandTime { get; set; }
    
        public virtual EmployeeGroup EmployeeGroup { get; set; }
    }
}
