//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> FCAmount { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
        public bool IsIncreaseTransaction { get; set; }
        public int Status { get; set; }
        public int StoreId { get; set; }
        public int BrandId { get; set; }
        public string UserId { get; set; }
        public int TransactionType { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
