//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATOrderMapping
    {
        public int ID { get; set; }
        public int RentID { get; set; }
        public int InvoiceID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual VATOrder VATOrder { get; set; }
    }
}
