//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebElementType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebElementType()
        {
            this.WebElements = new HashSet<WebElement>();
        }
    
        public int Id { get; set; }
        public Nullable<int> WebElementId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Template { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> ShowOnContentPage { get; set; }
        public string ImageUrl { get; set; }
        public string Link { get; set; }
        public Nullable<int> BrandId { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebElement> WebElements { get; set; }
    }
}
