//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoterDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCashbackDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerCashbackDetail()
        {
            this.PromotionAppliedDetails = new HashSet<PromotionAppliedDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CashbackAccountType { get; set; }
        public Nullable<int> CashbackType { get; set; }
        public Nullable<double> CashbackPer1000VND { get; set; }
        public Nullable<double> CashbackPercentOfOrder { get; set; }
        public Nullable<double> CashbackByRankAmount { get; set; }
        public string RankSID { get; set; }
        public Nullable<double> CashbackByCardRechargeRate { get; set; }
        public Nullable<double> CardRechargeRate { get; set; }
        public Nullable<double> CashbackPercentOfCardRecharge { get; set; }
        public Nullable<double> CashbackBySegment { get; set; }
        public Nullable<int> SegmentID { get; set; }
        public string SegmentSID { get; set; }
        public Nullable<int> PromotionDetailID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionAppliedDetail> PromotionAppliedDetails { get; set; }
        public virtual PromotionDetail PromotionDetail { get; set; }
    }
}
