//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoterDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftAppliedDetail
    {
        public int PromotionAppliedDetailID { get; set; }
        public int ProductIID { get; set; }
        public string ProductSID { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PromotionAppliedDetail PromotionAppliedDetail { get; set; }
    }
}
