//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoterDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiftDetail()
        {
            this.GiftDetails1 = new HashSet<GiftDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductIID { get; set; }
        public Nullable<int> PromotionDetailID { get; set; }
        public string ProductSID { get; set; }
        public Nullable<double> ProductAmount { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<int> VoucherAmount { get; set; }
        public Nullable<bool> IsGiftVoucher { get; set; }
        public Nullable<int> AndDetailID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftDetail> GiftDetails1 { get; set; }
        public virtual GiftDetail GiftDetail1 { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual Product Product { get; set; }
        public virtual PromotionDetail PromotionDetail { get; set; }
    }
}
