//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoterDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionStoreRule
    {
        public int ValidationRuleID { get; set; }
        public int StoreIID { get; set; }
        public string StoreSID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual ValidationRule ValidationRule { get; set; }
    }
}
