//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoterDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionAppliedDetail
    {
        public int Id { get; set; }
        public Nullable<int> PromotionType { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<int> RedemptionId { get; set; }
        public Nullable<int> RedemptionRollbackId { get; set; }
        public string VoucherCode { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<int> GiftAmount { get; set; }
        public string GiftProductCodes { get; set; }
        public string CouponCodes { get; set; }
        public Nullable<double> CouponTotalAmount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual Redemption Redemption { get; set; }
        public virtual RedemptionRollback RedemptionRollback { get; set; }
    }
}
