//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoterDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValidationRule()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.Promotions = new HashSet<Promotion>();
            this.ValidationRule1 = new HashSet<ValidationRule>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SegmentRuleOp { get; set; }
        public string InSegmentId { get; set; }
        public string NotInSegmentId { get; set; }
        public Nullable<int> ProductRuleOp { get; set; }
        public string ProductCodePattern { get; set; }
        public Nullable<double> MinProductPrice { get; set; }
        public Nullable<double> MaxProductPrice { get; set; }
        public Nullable<int> MinProductQuantity { get; set; }
        public Nullable<int> MaxProductQuantity { get; set; }
        public Nullable<int> OrderRuleOp { get; set; }
        public Nullable<double> MinOrderAmount { get; set; }
        public Nullable<double> MaxOrderAmount { get; set; }
        public Nullable<int> MinOrderProductQuantity { get; set; }
        public Nullable<int> MaxOrderProductQuantity { get; set; }
        public Nullable<int> RedemptionRuleOp { get; set; }
        public Nullable<int> MinRedeemTimes { get; set; }
        public Nullable<int> MaxRedeemTimes { get; set; }
        public Nullable<int> GeneralRuleOp { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string ListApplyHours { get; set; }
        public string ApplyStoresId { get; set; }
        public string ExceptDates { get; set; }
        public string ExceptDOWs { get; set; }
        public Nullable<int> AnotherRuleOp { get; set; }
        public Nullable<int> AnotherRuleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> Campaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidationRule> ValidationRule1 { get; set; }
        public virtual ValidationRule ValidationRule2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
