//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoterDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> PromotionDetailId { get; set; }
        public Nullable<int> ValidationRuleId { get; set; }
        public string AssetsObject { get; set; }
        public string MetadataObject { get; set; }
        public Nullable<bool> IsGotten { get; set; }
        public Nullable<int> UsingTimes { get; set; }
        public Nullable<int> UsedTimes { get; set; }
        public Nullable<bool> Deactive { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual PromotionDetail PromotionDetail { get; set; }
        public virtual ValidationRule ValidationRule { get; set; }
    }
}
