//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoterDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.GiftDetails = new HashSet<GiftDetail>();
            this.PromotionAppliedDetails = new HashSet<PromotionAppliedDetail>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> VoucherConfigID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public Nullable<int> ValidationRuleID { get; set; }
        public Nullable<int> PromotionDetailID { get; set; }
        public string AssetsObject { get; set; }
        public string MetadataObject { get; set; }
        public Nullable<bool> IsGotten { get; set; }
        public Nullable<int> UsingTimes { get; set; }
        public Nullable<int> UsedTimes { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftDetail> GiftDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionAppliedDetail> PromotionAppliedDetails { get; set; }
        public virtual PromotionDetail PromotionDetail { get; set; }
        public virtual ValidationRule ValidationRule { get; set; }
        public virtual VoucherConfig VoucherConfig { get; set; }
    }
}
