
// Generated helper templates
// Generated items
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CustomerFeedbackViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\WebPageViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\WebMenuCategoryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\WebMenuViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\WebElementTypeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\WebElementViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\WebCustomerFeedbackViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\WardViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\VoucherViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ViewCounterViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\VATOrderMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\VATOrderViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\UserViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TransactionViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TokenUserViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TimeModeTypeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TimeModeRuleViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TimeFrameViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ThemeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TemplateRuleMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TemplateReportProductItemMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TemplateDetailMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TagMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\TagViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\SystemPartnerMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\sysdiagramViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\SubRentGroupViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreWebViewCounterViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreWebSettingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreWebRouteModelViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreWebRouteViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreUserViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreThemeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreGroupMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreGroupViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreDomainViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\StoreViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\SalaryRuleViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\SalaryHourViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\RoomFloorViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\RoomCategoryPriceGroupMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\RoomCategoryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\RoomViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\RoleViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ReportTrackingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\RatingStarViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\RatingProductViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProvinceViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProviderProductItemMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProviderViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PromotionStoreMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PromotionDetailViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PromotionViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProfileViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductSpecificationViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductItemCompositionMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductItemCategoryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductImageCollectionItemMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductImageCollectionViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductImageViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductDetailMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductComboDetailViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductCollectionItemMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductCollectionViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductCategoryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ProductViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PriceNightViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PriceGroupViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PriceAdditionViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PosFileViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PosConfigViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PosViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PaySlipTemplateViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PaySlipItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PayslipAttributeMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PayslipAttributeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PaySlipViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PayrollPeriodViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PayrollDetailViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PayrollCategoryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PaymentReportViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PaymentPartnerViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PaymentViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PartnerMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\PartnerViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\OrderPromotionMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\OrderGroupViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\OrderFeeItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\OrderDetailPromotionMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\OrderDetailViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\OrderViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\NotificationViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\MenuViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\MembershipCardTypeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\MembershipCardViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\MachineConnectViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\LanguageValueViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\LanguageKeyViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\LanguageViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\InventoryTemplateReportViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\InventoryReceiptItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\InventoryReceiptViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\InventoryDateReportItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\InventoryDateReportViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\InventoryCheckingItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\InventoryCheckingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ImageCollectionItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ImageCollectionViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\GuestViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\GroupViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\FingerScanMachineViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\FavoritedViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\EventLocationViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\EmployeeInStoreViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\EmployeeGroupViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\EmployeeFingerViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\EmployeeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DistrictViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DeviceViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DeliveryInformationViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DeliveryInfoViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DayModeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DateReportViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DateProductItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DateProductViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\DateHotelReportViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CustomerTypeViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CustomerStoreReportMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CustomerProductMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CustomerFilterViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CustomerViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CouponProviderViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CouponCampaignViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CouponViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CostInventoryMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CostCategoryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CostViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ContactViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CheckFingerViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CategoryExtraMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\CategoryExtraViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\BrandViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\BlogPostImageViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\BlogPostCollectionItemMappingViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\BlogPostCollectionItemViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\BlogPostCollectionViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\BlogPostViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\BlogCategoryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\AttendanceDateViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\AttendanceViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\AspNetUserViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\AspNetUserLoginViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\AspNetUserClaimViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\AspNetRoleViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ArticleViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\AreaDeliveryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\ApplicationViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\AccountViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\C__MigrationHistoryViewModel.txt
// TNT.DataServiceTemplate\DataServiceTest\ViewModels\BaseViewModelGen.cs
