using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TNT.IoContainer.Container;
using AutoMapper;
using System.Web;
using DataServiceTest.Models;
using DataServiceTest.Models.Repositories;
using DataServiceTest.Models.Services;
using DataServiceTest.Managers;
using DataServiceTest.ViewModels;

namespace DataServiceTest.Global
{
	public static partial class G
	{
		public static IMapper Mapper;
		public static ITContainer TContainer;
		public static void DefaultConfigure()
		{
			ConfigureAutomapper();
			ConfigureIoContainer();
		}
		
		private static List<Action<IMapperConfigurationExpression>> MapperConfigs { get; set; }
		= new List<Action<IMapperConfigurationExpression>>()
		{
			cfg =>
			{
				cfg.CreateMap<Models.C__MigrationHistory, C__MigrationHistoryViewModel>().ReverseMap();
				cfg.CreateMap<Models.C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4, C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel>().ReverseMap();
				cfg.CreateMap<Models.Account, AccountViewModel>().ReverseMap();
				cfg.CreateMap<Models.Application, ApplicationViewModel>().ReverseMap();
				cfg.CreateMap<Models.AreaDelivery, AreaDeliveryViewModel>().ReverseMap();
				cfg.CreateMap<Models.Article, ArticleViewModel>().ReverseMap();
				cfg.CreateMap<Models.AspNetRole, AspNetRoleViewModel>().ReverseMap();
				cfg.CreateMap<Models.AspNetUserClaim, AspNetUserClaimViewModel>().ReverseMap();
				cfg.CreateMap<Models.AspNetUserLogin, AspNetUserLoginViewModel>().ReverseMap();
				cfg.CreateMap<Models.AspNetUser, AspNetUserViewModel>().ReverseMap();
				cfg.CreateMap<Models.Attendance, AttendanceViewModel>().ReverseMap();
				cfg.CreateMap<Models.AttendanceDate, AttendanceDateViewModel>().ReverseMap();
				cfg.CreateMap<Models.BlogCategory, BlogCategoryViewModel>().ReverseMap();
				cfg.CreateMap<Models.BlogPost, BlogPostViewModel>().ReverseMap();
				cfg.CreateMap<Models.BlogPostCollection, BlogPostCollectionViewModel>().ReverseMap();
				cfg.CreateMap<Models.BlogPostCollectionItem, BlogPostCollectionItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.BlogPostCollectionItemMapping, BlogPostCollectionItemMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.BlogPostImage, BlogPostImageViewModel>().ReverseMap();
				cfg.CreateMap<Models.Brand, BrandViewModel>().ReverseMap();
				cfg.CreateMap<Models.CategoryExtra, CategoryExtraViewModel>().ReverseMap();
				cfg.CreateMap<Models.CategoryExtraMapping, CategoryExtraMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.CheckFinger, CheckFingerViewModel>().ReverseMap();
				cfg.CreateMap<Models.Contact, ContactViewModel>().ReverseMap();
				cfg.CreateMap<Models.Cost, CostViewModel>().ReverseMap();
				cfg.CreateMap<Models.CostCategory, CostCategoryViewModel>().ReverseMap();
				cfg.CreateMap<Models.CostInventoryMapping, CostInventoryMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.Coupon, CouponViewModel>().ReverseMap();
				cfg.CreateMap<Models.CouponCampaign, CouponCampaignViewModel>().ReverseMap();
				cfg.CreateMap<Models.CouponProvider, CouponProviderViewModel>().ReverseMap();
				cfg.CreateMap<Models.Customer, CustomerViewModel>().ReverseMap();
				cfg.CreateMap<Models.CustomerFilter, CustomerFilterViewModel>().ReverseMap();
				cfg.CreateMap<Models.CustomerProductMapping, CustomerProductMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.CustomerStoreReportMapping, CustomerStoreReportMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.CustomerType, CustomerTypeViewModel>().ReverseMap();
				cfg.CreateMap<Models.DateHotelReport, DateHotelReportViewModel>().ReverseMap();
				cfg.CreateMap<Models.DateProduct, DateProductViewModel>().ReverseMap();
				cfg.CreateMap<Models.DateProductItem, DateProductItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.DateReport, DateReportViewModel>().ReverseMap();
				cfg.CreateMap<Models.DayMode, DayModeViewModel>().ReverseMap();
				cfg.CreateMap<Models.DeliveryInfo, DeliveryInfoViewModel>().ReverseMap();
				cfg.CreateMap<Models.DeliveryInformation, DeliveryInformationViewModel>().ReverseMap();
				cfg.CreateMap<Models.Device, DeviceViewModel>().ReverseMap();
				cfg.CreateMap<Models.District, DistrictViewModel>().ReverseMap();
				cfg.CreateMap<Models.Employee, EmployeeViewModel>().ReverseMap();
				cfg.CreateMap<Models.EmployeeFinger, EmployeeFingerViewModel>().ReverseMap();
				cfg.CreateMap<Models.EmployeeGroup, EmployeeGroupViewModel>().ReverseMap();
				cfg.CreateMap<Models.EmployeeInStore, EmployeeInStoreViewModel>().ReverseMap();
				cfg.CreateMap<Models.EventLocation, EventLocationViewModel>().ReverseMap();
				cfg.CreateMap<Models.Favorited, FavoritedViewModel>().ReverseMap();
				cfg.CreateMap<Models.FingerScanMachine, FingerScanMachineViewModel>().ReverseMap();
				cfg.CreateMap<Models.Group, GroupViewModel>().ReverseMap();
				cfg.CreateMap<Models.Guest, GuestViewModel>().ReverseMap();
				cfg.CreateMap<Models.ImageCollection, ImageCollectionViewModel>().ReverseMap();
				cfg.CreateMap<Models.ImageCollectionItem, ImageCollectionItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.InventoryChecking, InventoryCheckingViewModel>().ReverseMap();
				cfg.CreateMap<Models.InventoryCheckingItem, InventoryCheckingItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.InventoryDateReport, InventoryDateReportViewModel>().ReverseMap();
				cfg.CreateMap<Models.InventoryDateReportItem, InventoryDateReportItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.InventoryReceipt, InventoryReceiptViewModel>().ReverseMap();
				cfg.CreateMap<Models.InventoryReceiptItem, InventoryReceiptItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.InventoryTemplateReport, InventoryTemplateReportViewModel>().ReverseMap();
				cfg.CreateMap<Models.Language, LanguageViewModel>().ReverseMap();
				cfg.CreateMap<Models.LanguageKey, LanguageKeyViewModel>().ReverseMap();
				cfg.CreateMap<Models.LanguageValue, LanguageValueViewModel>().ReverseMap();
				cfg.CreateMap<Models.MachineConnect, MachineConnectViewModel>().ReverseMap();
				cfg.CreateMap<Models.MembershipCard, MembershipCardViewModel>().ReverseMap();
				cfg.CreateMap<Models.MembershipCardType, MembershipCardTypeViewModel>().ReverseMap();
				cfg.CreateMap<Models.Menu, MenuViewModel>().ReverseMap();
				cfg.CreateMap<Models.Notification, NotificationViewModel>().ReverseMap();
				cfg.CreateMap<Models.Order, OrderViewModel>().ReverseMap();
				cfg.CreateMap<Models.OrderDetail, OrderDetailViewModel>().ReverseMap();
				cfg.CreateMap<Models.OrderDetailPromotionMapping, OrderDetailPromotionMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.OrderFeeItem, OrderFeeItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.OrderGroup, OrderGroupViewModel>().ReverseMap();
				cfg.CreateMap<Models.OrderPromotionMapping, OrderPromotionMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.Partner, PartnerViewModel>().ReverseMap();
				cfg.CreateMap<Models.PartnerMapping, PartnerMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.Payment, PaymentViewModel>().ReverseMap();
				cfg.CreateMap<Models.PaymentPartner, PaymentPartnerViewModel>().ReverseMap();
				cfg.CreateMap<Models.PaymentReport, PaymentReportViewModel>().ReverseMap();
				cfg.CreateMap<Models.PayrollCategory, PayrollCategoryViewModel>().ReverseMap();
				cfg.CreateMap<Models.PayrollDetail, PayrollDetailViewModel>().ReverseMap();
				cfg.CreateMap<Models.PayrollPeriod, PayrollPeriodViewModel>().ReverseMap();
				cfg.CreateMap<Models.PaySlip, PaySlipViewModel>().ReverseMap();
				cfg.CreateMap<Models.PayslipAttribute, PayslipAttributeViewModel>().ReverseMap();
				cfg.CreateMap<Models.PayslipAttributeMapping, PayslipAttributeMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.PaySlipItem, PaySlipItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.PaySlipTemplate, PaySlipTemplateViewModel>().ReverseMap();
				cfg.CreateMap<Models.Pos, PosViewModel>().ReverseMap();
				cfg.CreateMap<Models.PosConfig, PosConfigViewModel>().ReverseMap();
				cfg.CreateMap<Models.PosFile, PosFileViewModel>().ReverseMap();
				cfg.CreateMap<Models.PriceAddition, PriceAdditionViewModel>().ReverseMap();
				cfg.CreateMap<Models.PriceGroup, PriceGroupViewModel>().ReverseMap();
				cfg.CreateMap<Models.PriceNight, PriceNightViewModel>().ReverseMap();
				cfg.CreateMap<Models.Product, ProductViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductCategory, ProductCategoryViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductCollection, ProductCollectionViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductCollectionItemMapping, ProductCollectionItemMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductComboDetail, ProductComboDetailViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductDetailMapping, ProductDetailMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductImage, ProductImageViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductImageCollection, ProductImageCollectionViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductImageCollectionItemMapping, ProductImageCollectionItemMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductItem, ProductItemViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductItemCategory, ProductItemCategoryViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductItemCompositionMapping, ProductItemCompositionMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProductSpecification, ProductSpecificationViewModel>().ReverseMap();
				cfg.CreateMap<Models.Profile, ProfileViewModel>().ReverseMap();
				cfg.CreateMap<Models.Promotion, PromotionViewModel>().ReverseMap();
				cfg.CreateMap<Models.PromotionDetail, PromotionDetailViewModel>().ReverseMap();
				cfg.CreateMap<Models.PromotionStoreMapping, PromotionStoreMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.Provider, ProviderViewModel>().ReverseMap();
				cfg.CreateMap<Models.ProviderProductItemMapping, ProviderProductItemMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.Province, ProvinceViewModel>().ReverseMap();
				cfg.CreateMap<Models.RatingProduct, RatingProductViewModel>().ReverseMap();
				cfg.CreateMap<Models.RatingStar, RatingStarViewModel>().ReverseMap();
				cfg.CreateMap<Models.ReportTracking, ReportTrackingViewModel>().ReverseMap();
				cfg.CreateMap<Models.Role, RoleViewModel>().ReverseMap();
				cfg.CreateMap<Models.Room, RoomViewModel>().ReverseMap();
				cfg.CreateMap<Models.RoomCategory, RoomCategoryViewModel>().ReverseMap();
				cfg.CreateMap<Models.RoomCategoryPriceGroupMapping, RoomCategoryPriceGroupMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.RoomFloor, RoomFloorViewModel>().ReverseMap();
				cfg.CreateMap<Models.SalaryHour, SalaryHourViewModel>().ReverseMap();
				cfg.CreateMap<Models.SalaryRule, SalaryRuleViewModel>().ReverseMap();
				cfg.CreateMap<Models.Store, StoreViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreDomain, StoreDomainViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreGroup, StoreGroupViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreGroupMapping, StoreGroupMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreTheme, StoreThemeViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreUser, StoreUserViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreWebRoute, StoreWebRouteViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreWebRouteModel, StoreWebRouteModelViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreWebSetting, StoreWebSettingViewModel>().ReverseMap();
				cfg.CreateMap<Models.StoreWebViewCounter, StoreWebViewCounterViewModel>().ReverseMap();
				cfg.CreateMap<Models.SubRentGroup, SubRentGroupViewModel>().ReverseMap();
				cfg.CreateMap<Models.sysdiagram, sysdiagramViewModel>().ReverseMap();
				cfg.CreateMap<Models.SystemPartnerMapping, SystemPartnerMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.Tag, TagViewModel>().ReverseMap();
				cfg.CreateMap<Models.TagMapping, TagMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.TemplateDetailMapping, TemplateDetailMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.TemplateReportProductItemMapping, TemplateReportProductItemMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.TemplateRuleMapping, TemplateRuleMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.Theme, ThemeViewModel>().ReverseMap();
				cfg.CreateMap<Models.TimeFrame, TimeFrameViewModel>().ReverseMap();
				cfg.CreateMap<Models.TimeModeRule, TimeModeRuleViewModel>().ReverseMap();
				cfg.CreateMap<Models.TimeModeType, TimeModeTypeViewModel>().ReverseMap();
				cfg.CreateMap<Models.TokenUser, TokenUserViewModel>().ReverseMap();
				cfg.CreateMap<Models.Transaction, TransactionViewModel>().ReverseMap();
				cfg.CreateMap<Models.User, UserViewModel>().ReverseMap();
				cfg.CreateMap<Models.VATOrder, VATOrderViewModel>().ReverseMap();
				cfg.CreateMap<Models.VATOrderMapping, VATOrderMappingViewModel>().ReverseMap();
				cfg.CreateMap<Models.ViewCounter, ViewCounterViewModel>().ReverseMap();
				cfg.CreateMap<Models.Voucher, VoucherViewModel>().ReverseMap();
				cfg.CreateMap<Models.Ward, WardViewModel>().ReverseMap();
				cfg.CreateMap<Models.WebCustomerFeedback, WebCustomerFeedbackViewModel>().ReverseMap();
				cfg.CreateMap<Models.WebElement, WebElementViewModel>().ReverseMap();
				cfg.CreateMap<Models.WebElementType, WebElementTypeViewModel>().ReverseMap();
				cfg.CreateMap<Models.WebMenu, WebMenuViewModel>().ReverseMap();
				cfg.CreateMap<Models.WebMenuCategory, WebMenuCategoryViewModel>().ReverseMap();
				cfg.CreateMap<Models.WebPage, WebPageViewModel>().ReverseMap();
				cfg.CreateMap<Models.CustomerFeedback, CustomerFeedbackViewModel>().ReverseMap();
			}
		};
		public static void AddMapperConfig(Action<IMapperConfigurationExpression> cfg)
		{
			MapperConfigs.Add(cfg);
		}
		private static void ConfigureAutomapper()
		{
			//AutoMapper
			var mapConfig = new MapperConfiguration(cfg =>
			{
				foreach (var c in MapperConfigs)
				{
					c.Invoke(cfg);
				}
			});
			G.Mapper = mapConfig.CreateMapper();
			
		}
		
		private static void ConfigureIoContainer()
		{
			//IoContainer
			G.TContainer = new TContainer();
			G.TContainer.RegisterRequestScopeHandlerModule();
			G.TContainer.RegisterType<IUnitOfWork, UnitOfWork>();
			G.TContainer.RegisterType<IC__MigrationHistoryRepository, C__MigrationHistoryRepository>();
			G.TContainer.RegisterType<IC_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Repository, C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Repository>();
			G.TContainer.RegisterType<IAccountRepository, AccountRepository>();
			G.TContainer.RegisterType<IApplicationRepository, ApplicationRepository>();
			G.TContainer.RegisterType<IAreaDeliveryRepository, AreaDeliveryRepository>();
			G.TContainer.RegisterType<IArticleRepository, ArticleRepository>();
			G.TContainer.RegisterType<IAspNetRoleRepository, AspNetRoleRepository>();
			G.TContainer.RegisterType<IAspNetUserClaimRepository, AspNetUserClaimRepository>();
			G.TContainer.RegisterType<IAspNetUserLoginRepository, AspNetUserLoginRepository>();
			G.TContainer.RegisterType<IAspNetUserRepository, AspNetUserRepository>();
			G.TContainer.RegisterType<IAttendanceRepository, AttendanceRepository>();
			G.TContainer.RegisterType<IAttendanceDateRepository, AttendanceDateRepository>();
			G.TContainer.RegisterType<IBlogCategoryRepository, BlogCategoryRepository>();
			G.TContainer.RegisterType<IBlogPostRepository, BlogPostRepository>();
			G.TContainer.RegisterType<IBlogPostCollectionRepository, BlogPostCollectionRepository>();
			G.TContainer.RegisterType<IBlogPostCollectionItemRepository, BlogPostCollectionItemRepository>();
			G.TContainer.RegisterType<IBlogPostCollectionItemMappingRepository, BlogPostCollectionItemMappingRepository>();
			G.TContainer.RegisterType<IBlogPostImageRepository, BlogPostImageRepository>();
			G.TContainer.RegisterType<IBrandRepository, BrandRepository>();
			G.TContainer.RegisterType<ICategoryExtraRepository, CategoryExtraRepository>();
			G.TContainer.RegisterType<ICategoryExtraMappingRepository, CategoryExtraMappingRepository>();
			G.TContainer.RegisterType<ICheckFingerRepository, CheckFingerRepository>();
			G.TContainer.RegisterType<IContactRepository, ContactRepository>();
			G.TContainer.RegisterType<ICostRepository, CostRepository>();
			G.TContainer.RegisterType<ICostCategoryRepository, CostCategoryRepository>();
			G.TContainer.RegisterType<ICostInventoryMappingRepository, CostInventoryMappingRepository>();
			G.TContainer.RegisterType<ICouponRepository, CouponRepository>();
			G.TContainer.RegisterType<ICouponCampaignRepository, CouponCampaignRepository>();
			G.TContainer.RegisterType<ICouponProviderRepository, CouponProviderRepository>();
			G.TContainer.RegisterType<ICustomerRepository, CustomerRepository>();
			G.TContainer.RegisterType<ICustomerFilterRepository, CustomerFilterRepository>();
			G.TContainer.RegisterType<ICustomerProductMappingRepository, CustomerProductMappingRepository>();
			G.TContainer.RegisterType<ICustomerStoreReportMappingRepository, CustomerStoreReportMappingRepository>();
			G.TContainer.RegisterType<ICustomerTypeRepository, CustomerTypeRepository>();
			G.TContainer.RegisterType<IDateHotelReportRepository, DateHotelReportRepository>();
			G.TContainer.RegisterType<IDateProductRepository, DateProductRepository>();
			G.TContainer.RegisterType<IDateProductItemRepository, DateProductItemRepository>();
			G.TContainer.RegisterType<IDateReportRepository, DateReportRepository>();
			G.TContainer.RegisterType<IDayModeRepository, DayModeRepository>();
			G.TContainer.RegisterType<IDeliveryInfoRepository, DeliveryInfoRepository>();
			G.TContainer.RegisterType<IDeliveryInformationRepository, DeliveryInformationRepository>();
			G.TContainer.RegisterType<IDeviceRepository, DeviceRepository>();
			G.TContainer.RegisterType<IDistrictRepository, DistrictRepository>();
			G.TContainer.RegisterType<IEmployeeRepository, EmployeeRepository>();
			G.TContainer.RegisterType<IEmployeeFingerRepository, EmployeeFingerRepository>();
			G.TContainer.RegisterType<IEmployeeGroupRepository, EmployeeGroupRepository>();
			G.TContainer.RegisterType<IEmployeeInStoreRepository, EmployeeInStoreRepository>();
			G.TContainer.RegisterType<IEventLocationRepository, EventLocationRepository>();
			G.TContainer.RegisterType<IFavoritedRepository, FavoritedRepository>();
			G.TContainer.RegisterType<IFingerScanMachineRepository, FingerScanMachineRepository>();
			G.TContainer.RegisterType<IGroupRepository, GroupRepository>();
			G.TContainer.RegisterType<IGuestRepository, GuestRepository>();
			G.TContainer.RegisterType<IImageCollectionRepository, ImageCollectionRepository>();
			G.TContainer.RegisterType<IImageCollectionItemRepository, ImageCollectionItemRepository>();
			G.TContainer.RegisterType<IInventoryCheckingRepository, InventoryCheckingRepository>();
			G.TContainer.RegisterType<IInventoryCheckingItemRepository, InventoryCheckingItemRepository>();
			G.TContainer.RegisterType<IInventoryDateReportRepository, InventoryDateReportRepository>();
			G.TContainer.RegisterType<IInventoryDateReportItemRepository, InventoryDateReportItemRepository>();
			G.TContainer.RegisterType<IInventoryReceiptRepository, InventoryReceiptRepository>();
			G.TContainer.RegisterType<IInventoryReceiptItemRepository, InventoryReceiptItemRepository>();
			G.TContainer.RegisterType<IInventoryTemplateReportRepository, InventoryTemplateReportRepository>();
			G.TContainer.RegisterType<ILanguageRepository, LanguageRepository>();
			G.TContainer.RegisterType<ILanguageKeyRepository, LanguageKeyRepository>();
			G.TContainer.RegisterType<ILanguageValueRepository, LanguageValueRepository>();
			G.TContainer.RegisterType<IMachineConnectRepository, MachineConnectRepository>();
			G.TContainer.RegisterType<IMembershipCardRepository, MembershipCardRepository>();
			G.TContainer.RegisterType<IMembershipCardTypeRepository, MembershipCardTypeRepository>();
			G.TContainer.RegisterType<IMenuRepository, MenuRepository>();
			G.TContainer.RegisterType<INotificationRepository, NotificationRepository>();
			G.TContainer.RegisterType<IOrderRepository, OrderRepository>();
			G.TContainer.RegisterType<IOrderDetailRepository, OrderDetailRepository>();
			G.TContainer.RegisterType<IOrderDetailPromotionMappingRepository, OrderDetailPromotionMappingRepository>();
			G.TContainer.RegisterType<IOrderFeeItemRepository, OrderFeeItemRepository>();
			G.TContainer.RegisterType<IOrderGroupRepository, OrderGroupRepository>();
			G.TContainer.RegisterType<IOrderPromotionMappingRepository, OrderPromotionMappingRepository>();
			G.TContainer.RegisterType<IPartnerRepository, PartnerRepository>();
			G.TContainer.RegisterType<IPartnerMappingRepository, PartnerMappingRepository>();
			G.TContainer.RegisterType<IPaymentRepository, PaymentRepository>();
			G.TContainer.RegisterType<IPaymentPartnerRepository, PaymentPartnerRepository>();
			G.TContainer.RegisterType<IPaymentReportRepository, PaymentReportRepository>();
			G.TContainer.RegisterType<IPayrollCategoryRepository, PayrollCategoryRepository>();
			G.TContainer.RegisterType<IPayrollDetailRepository, PayrollDetailRepository>();
			G.TContainer.RegisterType<IPayrollPeriodRepository, PayrollPeriodRepository>();
			G.TContainer.RegisterType<IPaySlipRepository, PaySlipRepository>();
			G.TContainer.RegisterType<IPayslipAttributeRepository, PayslipAttributeRepository>();
			G.TContainer.RegisterType<IPayslipAttributeMappingRepository, PayslipAttributeMappingRepository>();
			G.TContainer.RegisterType<IPaySlipItemRepository, PaySlipItemRepository>();
			G.TContainer.RegisterType<IPaySlipTemplateRepository, PaySlipTemplateRepository>();
			G.TContainer.RegisterType<IPosRepository, PosRepository>();
			G.TContainer.RegisterType<IPosConfigRepository, PosConfigRepository>();
			G.TContainer.RegisterType<IPosFileRepository, PosFileRepository>();
			G.TContainer.RegisterType<IPriceAdditionRepository, PriceAdditionRepository>();
			G.TContainer.RegisterType<IPriceGroupRepository, PriceGroupRepository>();
			G.TContainer.RegisterType<IPriceNightRepository, PriceNightRepository>();
			G.TContainer.RegisterType<IProductRepository, ProductRepository>();
			G.TContainer.RegisterType<IProductCategoryRepository, ProductCategoryRepository>();
			G.TContainer.RegisterType<IProductCollectionRepository, ProductCollectionRepository>();
			G.TContainer.RegisterType<IProductCollectionItemMappingRepository, ProductCollectionItemMappingRepository>();
			G.TContainer.RegisterType<IProductComboDetailRepository, ProductComboDetailRepository>();
			G.TContainer.RegisterType<IProductDetailMappingRepository, ProductDetailMappingRepository>();
			G.TContainer.RegisterType<IProductImageRepository, ProductImageRepository>();
			G.TContainer.RegisterType<IProductImageCollectionRepository, ProductImageCollectionRepository>();
			G.TContainer.RegisterType<IProductImageCollectionItemMappingRepository, ProductImageCollectionItemMappingRepository>();
			G.TContainer.RegisterType<IProductItemRepository, ProductItemRepository>();
			G.TContainer.RegisterType<IProductItemCategoryRepository, ProductItemCategoryRepository>();
			G.TContainer.RegisterType<IProductItemCompositionMappingRepository, ProductItemCompositionMappingRepository>();
			G.TContainer.RegisterType<IProductSpecificationRepository, ProductSpecificationRepository>();
			G.TContainer.RegisterType<IProfileRepository, ProfileRepository>();
			G.TContainer.RegisterType<IPromotionRepository, PromotionRepository>();
			G.TContainer.RegisterType<IPromotionDetailRepository, PromotionDetailRepository>();
			G.TContainer.RegisterType<IPromotionStoreMappingRepository, PromotionStoreMappingRepository>();
			G.TContainer.RegisterType<IProviderRepository, ProviderRepository>();
			G.TContainer.RegisterType<IProviderProductItemMappingRepository, ProviderProductItemMappingRepository>();
			G.TContainer.RegisterType<IProvinceRepository, ProvinceRepository>();
			G.TContainer.RegisterType<IRatingProductRepository, RatingProductRepository>();
			G.TContainer.RegisterType<IRatingStarRepository, RatingStarRepository>();
			G.TContainer.RegisterType<IReportTrackingRepository, ReportTrackingRepository>();
			G.TContainer.RegisterType<IRoleRepository, RoleRepository>();
			G.TContainer.RegisterType<IRoomRepository, RoomRepository>();
			G.TContainer.RegisterType<IRoomCategoryRepository, RoomCategoryRepository>();
			G.TContainer.RegisterType<IRoomCategoryPriceGroupMappingRepository, RoomCategoryPriceGroupMappingRepository>();
			G.TContainer.RegisterType<IRoomFloorRepository, RoomFloorRepository>();
			G.TContainer.RegisterType<ISalaryHourRepository, SalaryHourRepository>();
			G.TContainer.RegisterType<ISalaryRuleRepository, SalaryRuleRepository>();
			G.TContainer.RegisterType<IStoreRepository, StoreRepository>();
			G.TContainer.RegisterType<IStoreDomainRepository, StoreDomainRepository>();
			G.TContainer.RegisterType<IStoreGroupRepository, StoreGroupRepository>();
			G.TContainer.RegisterType<IStoreGroupMappingRepository, StoreGroupMappingRepository>();
			G.TContainer.RegisterType<IStoreThemeRepository, StoreThemeRepository>();
			G.TContainer.RegisterType<IStoreUserRepository, StoreUserRepository>();
			G.TContainer.RegisterType<IStoreWebRouteRepository, StoreWebRouteRepository>();
			G.TContainer.RegisterType<IStoreWebRouteModelRepository, StoreWebRouteModelRepository>();
			G.TContainer.RegisterType<IStoreWebSettingRepository, StoreWebSettingRepository>();
			G.TContainer.RegisterType<IStoreWebViewCounterRepository, StoreWebViewCounterRepository>();
			G.TContainer.RegisterType<ISubRentGroupRepository, SubRentGroupRepository>();
			G.TContainer.RegisterType<IsysdiagramRepository, sysdiagramRepository>();
			G.TContainer.RegisterType<ISystemPartnerMappingRepository, SystemPartnerMappingRepository>();
			G.TContainer.RegisterType<ITagRepository, TagRepository>();
			G.TContainer.RegisterType<ITagMappingRepository, TagMappingRepository>();
			G.TContainer.RegisterType<ITemplateDetailMappingRepository, TemplateDetailMappingRepository>();
			G.TContainer.RegisterType<ITemplateReportProductItemMappingRepository, TemplateReportProductItemMappingRepository>();
			G.TContainer.RegisterType<ITemplateRuleMappingRepository, TemplateRuleMappingRepository>();
			G.TContainer.RegisterType<IThemeRepository, ThemeRepository>();
			G.TContainer.RegisterType<ITimeFrameRepository, TimeFrameRepository>();
			G.TContainer.RegisterType<ITimeModeRuleRepository, TimeModeRuleRepository>();
			G.TContainer.RegisterType<ITimeModeTypeRepository, TimeModeTypeRepository>();
			G.TContainer.RegisterType<ITokenUserRepository, TokenUserRepository>();
			G.TContainer.RegisterType<ITransactionRepository, TransactionRepository>();
			G.TContainer.RegisterType<IUserRepository, UserRepository>();
			G.TContainer.RegisterType<IVATOrderRepository, VATOrderRepository>();
			G.TContainer.RegisterType<IVATOrderMappingRepository, VATOrderMappingRepository>();
			G.TContainer.RegisterType<IViewCounterRepository, ViewCounterRepository>();
			G.TContainer.RegisterType<IVoucherRepository, VoucherRepository>();
			G.TContainer.RegisterType<IWardRepository, WardRepository>();
			G.TContainer.RegisterType<IWebCustomerFeedbackRepository, WebCustomerFeedbackRepository>();
			G.TContainer.RegisterType<IWebElementRepository, WebElementRepository>();
			G.TContainer.RegisterType<IWebElementTypeRepository, WebElementTypeRepository>();
			G.TContainer.RegisterType<IWebMenuRepository, WebMenuRepository>();
			G.TContainer.RegisterType<IWebMenuCategoryRepository, WebMenuCategoryRepository>();
			G.TContainer.RegisterType<IWebPageRepository, WebPageRepository>();
			G.TContainer.RegisterType<ICustomerFeedbackRepository, CustomerFeedbackRepository>();
			G.TContainer.RegisterToPool<IC__MigrationHistoryService, C__MigrationHistoryService>(10, 100);
			G.TContainer.RegisterToPool<IC_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service, C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service>(10, 100);
			G.TContainer.RegisterToPool<IAccountService, AccountService>(10, 100);
			G.TContainer.RegisterToPool<IApplicationService, ApplicationService>(10, 100);
			G.TContainer.RegisterToPool<IAreaDeliveryService, AreaDeliveryService>(10, 100);
			G.TContainer.RegisterToPool<IArticleService, ArticleService>(10, 100);
			G.TContainer.RegisterToPool<IAspNetRoleService, AspNetRoleService>(10, 100);
			G.TContainer.RegisterToPool<IAspNetUserClaimService, AspNetUserClaimService>(10, 100);
			G.TContainer.RegisterToPool<IAspNetUserLoginService, AspNetUserLoginService>(10, 100);
			G.TContainer.RegisterToPool<IAspNetUserService, AspNetUserService>(10, 100);
			G.TContainer.RegisterToPool<IAttendanceService, AttendanceService>(10, 100);
			G.TContainer.RegisterToPool<IAttendanceDateService, AttendanceDateService>(10, 100);
			G.TContainer.RegisterToPool<IBlogCategoryService, BlogCategoryService>(10, 100);
			G.TContainer.RegisterToPool<IBlogPostService, BlogPostService>(10, 100);
			G.TContainer.RegisterToPool<IBlogPostCollectionService, BlogPostCollectionService>(10, 100);
			G.TContainer.RegisterToPool<IBlogPostCollectionItemService, BlogPostCollectionItemService>(10, 100);
			G.TContainer.RegisterToPool<IBlogPostCollectionItemMappingService, BlogPostCollectionItemMappingService>(10, 100);
			G.TContainer.RegisterToPool<IBlogPostImageService, BlogPostImageService>(10, 100);
			G.TContainer.RegisterToPool<IBrandService, BrandService>(10, 100);
			G.TContainer.RegisterToPool<ICategoryExtraService, CategoryExtraService>(10, 100);
			G.TContainer.RegisterToPool<ICategoryExtraMappingService, CategoryExtraMappingService>(10, 100);
			G.TContainer.RegisterToPool<ICheckFingerService, CheckFingerService>(10, 100);
			G.TContainer.RegisterToPool<IContactService, ContactService>(10, 100);
			G.TContainer.RegisterToPool<ICostService, CostService>(10, 100);
			G.TContainer.RegisterToPool<ICostCategoryService, CostCategoryService>(10, 100);
			G.TContainer.RegisterToPool<ICostInventoryMappingService, CostInventoryMappingService>(10, 100);
			G.TContainer.RegisterToPool<ICouponService, CouponService>(10, 100);
			G.TContainer.RegisterToPool<ICouponCampaignService, CouponCampaignService>(10, 100);
			G.TContainer.RegisterToPool<ICouponProviderService, CouponProviderService>(10, 100);
			G.TContainer.RegisterToPool<ICustomerService, CustomerService>(10, 100);
			G.TContainer.RegisterToPool<ICustomerFilterService, CustomerFilterService>(10, 100);
			G.TContainer.RegisterToPool<ICustomerProductMappingService, CustomerProductMappingService>(10, 100);
			G.TContainer.RegisterToPool<ICustomerStoreReportMappingService, CustomerStoreReportMappingService>(10, 100);
			G.TContainer.RegisterToPool<ICustomerTypeService, CustomerTypeService>(10, 100);
			G.TContainer.RegisterToPool<IDateHotelReportService, DateHotelReportService>(10, 100);
			G.TContainer.RegisterToPool<IDateProductService, DateProductService>(10, 100);
			G.TContainer.RegisterToPool<IDateProductItemService, DateProductItemService>(10, 100);
			G.TContainer.RegisterToPool<IDateReportService, DateReportService>(10, 100);
			G.TContainer.RegisterToPool<IDayModeService, DayModeService>(10, 100);
			G.TContainer.RegisterToPool<IDeliveryInfoService, DeliveryInfoService>(10, 100);
			G.TContainer.RegisterToPool<IDeliveryInformationService, DeliveryInformationService>(10, 100);
			G.TContainer.RegisterToPool<IDeviceService, DeviceService>(10, 100);
			G.TContainer.RegisterToPool<IDistrictService, DistrictService>(10, 100);
			G.TContainer.RegisterToPool<IEmployeeService, EmployeeService>(10, 100);
			G.TContainer.RegisterToPool<IEmployeeFingerService, EmployeeFingerService>(10, 100);
			G.TContainer.RegisterToPool<IEmployeeGroupService, EmployeeGroupService>(10, 100);
			G.TContainer.RegisterToPool<IEmployeeInStoreService, EmployeeInStoreService>(10, 100);
			G.TContainer.RegisterToPool<IEventLocationService, EventLocationService>(10, 100);
			G.TContainer.RegisterToPool<IFavoritedService, FavoritedService>(10, 100);
			G.TContainer.RegisterToPool<IFingerScanMachineService, FingerScanMachineService>(10, 100);
			G.TContainer.RegisterToPool<IGroupService, GroupService>(10, 100);
			G.TContainer.RegisterToPool<IGuestService, GuestService>(10, 100);
			G.TContainer.RegisterToPool<IImageCollectionService, ImageCollectionService>(10, 100);
			G.TContainer.RegisterToPool<IImageCollectionItemService, ImageCollectionItemService>(10, 100);
			G.TContainer.RegisterToPool<IInventoryCheckingService, InventoryCheckingService>(10, 100);
			G.TContainer.RegisterToPool<IInventoryCheckingItemService, InventoryCheckingItemService>(10, 100);
			G.TContainer.RegisterToPool<IInventoryDateReportService, InventoryDateReportService>(10, 100);
			G.TContainer.RegisterToPool<IInventoryDateReportItemService, InventoryDateReportItemService>(10, 100);
			G.TContainer.RegisterToPool<IInventoryReceiptService, InventoryReceiptService>(10, 100);
			G.TContainer.RegisterToPool<IInventoryReceiptItemService, InventoryReceiptItemService>(10, 100);
			G.TContainer.RegisterToPool<IInventoryTemplateReportService, InventoryTemplateReportService>(10, 100);
			G.TContainer.RegisterToPool<ILanguageService, LanguageService>(10, 100);
			G.TContainer.RegisterToPool<ILanguageKeyService, LanguageKeyService>(10, 100);
			G.TContainer.RegisterToPool<ILanguageValueService, LanguageValueService>(10, 100);
			G.TContainer.RegisterToPool<IMachineConnectService, MachineConnectService>(10, 100);
			G.TContainer.RegisterToPool<IMembershipCardService, MembershipCardService>(10, 100);
			G.TContainer.RegisterToPool<IMembershipCardTypeService, MembershipCardTypeService>(10, 100);
			G.TContainer.RegisterToPool<IMenuService, MenuService>(10, 100);
			G.TContainer.RegisterToPool<INotificationService, NotificationService>(10, 100);
			G.TContainer.RegisterToPool<IOrderService, OrderService>(10, 100);
			G.TContainer.RegisterToPool<IOrderDetailService, OrderDetailService>(10, 100);
			G.TContainer.RegisterToPool<IOrderDetailPromotionMappingService, OrderDetailPromotionMappingService>(10, 100);
			G.TContainer.RegisterToPool<IOrderFeeItemService, OrderFeeItemService>(10, 100);
			G.TContainer.RegisterToPool<IOrderGroupService, OrderGroupService>(10, 100);
			G.TContainer.RegisterToPool<IOrderPromotionMappingService, OrderPromotionMappingService>(10, 100);
			G.TContainer.RegisterToPool<IPartnerService, PartnerService>(10, 100);
			G.TContainer.RegisterToPool<IPartnerMappingService, PartnerMappingService>(10, 100);
			G.TContainer.RegisterToPool<IPaymentService, PaymentService>(10, 100);
			G.TContainer.RegisterToPool<IPaymentPartnerService, PaymentPartnerService>(10, 100);
			G.TContainer.RegisterToPool<IPaymentReportService, PaymentReportService>(10, 100);
			G.TContainer.RegisterToPool<IPayrollCategoryService, PayrollCategoryService>(10, 100);
			G.TContainer.RegisterToPool<IPayrollDetailService, PayrollDetailService>(10, 100);
			G.TContainer.RegisterToPool<IPayrollPeriodService, PayrollPeriodService>(10, 100);
			G.TContainer.RegisterToPool<IPaySlipService, PaySlipService>(10, 100);
			G.TContainer.RegisterToPool<IPayslipAttributeService, PayslipAttributeService>(10, 100);
			G.TContainer.RegisterToPool<IPayslipAttributeMappingService, PayslipAttributeMappingService>(10, 100);
			G.TContainer.RegisterToPool<IPaySlipItemService, PaySlipItemService>(10, 100);
			G.TContainer.RegisterToPool<IPaySlipTemplateService, PaySlipTemplateService>(10, 100);
			G.TContainer.RegisterToPool<IPosService, PosService>(10, 100);
			G.TContainer.RegisterToPool<IPosConfigService, PosConfigService>(10, 100);
			G.TContainer.RegisterToPool<IPosFileService, PosFileService>(10, 100);
			G.TContainer.RegisterToPool<IPriceAdditionService, PriceAdditionService>(10, 100);
			G.TContainer.RegisterToPool<IPriceGroupService, PriceGroupService>(10, 100);
			G.TContainer.RegisterToPool<IPriceNightService, PriceNightService>(10, 100);
			G.TContainer.RegisterToPool<IProductService, ProductService>(10, 100);
			G.TContainer.RegisterToPool<IProductCategoryService, ProductCategoryService>(10, 100);
			G.TContainer.RegisterToPool<IProductCollectionService, ProductCollectionService>(10, 100);
			G.TContainer.RegisterToPool<IProductCollectionItemMappingService, ProductCollectionItemMappingService>(10, 100);
			G.TContainer.RegisterToPool<IProductComboDetailService, ProductComboDetailService>(10, 100);
			G.TContainer.RegisterToPool<IProductDetailMappingService, ProductDetailMappingService>(10, 100);
			G.TContainer.RegisterToPool<IProductImageService, ProductImageService>(10, 100);
			G.TContainer.RegisterToPool<IProductImageCollectionService, ProductImageCollectionService>(10, 100);
			G.TContainer.RegisterToPool<IProductImageCollectionItemMappingService, ProductImageCollectionItemMappingService>(10, 100);
			G.TContainer.RegisterToPool<IProductItemService, ProductItemService>(10, 100);
			G.TContainer.RegisterToPool<IProductItemCategoryService, ProductItemCategoryService>(10, 100);
			G.TContainer.RegisterToPool<IProductItemCompositionMappingService, ProductItemCompositionMappingService>(10, 100);
			G.TContainer.RegisterToPool<IProductSpecificationService, ProductSpecificationService>(10, 100);
			G.TContainer.RegisterToPool<IProfileService, ProfileService>(10, 100);
			G.TContainer.RegisterToPool<IPromotionService, PromotionService>(10, 100);
			G.TContainer.RegisterToPool<IPromotionDetailService, PromotionDetailService>(10, 100);
			G.TContainer.RegisterToPool<IPromotionStoreMappingService, PromotionStoreMappingService>(10, 100);
			G.TContainer.RegisterToPool<IProviderService, ProviderService>(10, 100);
			G.TContainer.RegisterToPool<IProviderProductItemMappingService, ProviderProductItemMappingService>(10, 100);
			G.TContainer.RegisterToPool<IProvinceService, ProvinceService>(10, 100);
			G.TContainer.RegisterToPool<IRatingProductService, RatingProductService>(10, 100);
			G.TContainer.RegisterToPool<IRatingStarService, RatingStarService>(10, 100);
			G.TContainer.RegisterToPool<IReportTrackingService, ReportTrackingService>(10, 100);
			G.TContainer.RegisterToPool<IRoleService, RoleService>(10, 100);
			G.TContainer.RegisterToPool<IRoomService, RoomService>(10, 100);
			G.TContainer.RegisterToPool<IRoomCategoryService, RoomCategoryService>(10, 100);
			G.TContainer.RegisterToPool<IRoomCategoryPriceGroupMappingService, RoomCategoryPriceGroupMappingService>(10, 100);
			G.TContainer.RegisterToPool<IRoomFloorService, RoomFloorService>(10, 100);
			G.TContainer.RegisterToPool<ISalaryHourService, SalaryHourService>(10, 100);
			G.TContainer.RegisterToPool<ISalaryRuleService, SalaryRuleService>(10, 100);
			G.TContainer.RegisterToPool<IStoreService, StoreService>(10, 100);
			G.TContainer.RegisterToPool<IStoreDomainService, StoreDomainService>(10, 100);
			G.TContainer.RegisterToPool<IStoreGroupService, StoreGroupService>(10, 100);
			G.TContainer.RegisterToPool<IStoreGroupMappingService, StoreGroupMappingService>(10, 100);
			G.TContainer.RegisterToPool<IStoreThemeService, StoreThemeService>(10, 100);
			G.TContainer.RegisterToPool<IStoreUserService, StoreUserService>(10, 100);
			G.TContainer.RegisterToPool<IStoreWebRouteService, StoreWebRouteService>(10, 100);
			G.TContainer.RegisterToPool<IStoreWebRouteModelService, StoreWebRouteModelService>(10, 100);
			G.TContainer.RegisterToPool<IStoreWebSettingService, StoreWebSettingService>(10, 100);
			G.TContainer.RegisterToPool<IStoreWebViewCounterService, StoreWebViewCounterService>(10, 100);
			G.TContainer.RegisterToPool<ISubRentGroupService, SubRentGroupService>(10, 100);
			G.TContainer.RegisterToPool<IsysdiagramService, sysdiagramService>(10, 100);
			G.TContainer.RegisterToPool<ISystemPartnerMappingService, SystemPartnerMappingService>(10, 100);
			G.TContainer.RegisterToPool<ITagService, TagService>(10, 100);
			G.TContainer.RegisterToPool<ITagMappingService, TagMappingService>(10, 100);
			G.TContainer.RegisterToPool<ITemplateDetailMappingService, TemplateDetailMappingService>(10, 100);
			G.TContainer.RegisterToPool<ITemplateReportProductItemMappingService, TemplateReportProductItemMappingService>(10, 100);
			G.TContainer.RegisterToPool<ITemplateRuleMappingService, TemplateRuleMappingService>(10, 100);
			G.TContainer.RegisterToPool<IThemeService, ThemeService>(10, 100);
			G.TContainer.RegisterToPool<ITimeFrameService, TimeFrameService>(10, 100);
			G.TContainer.RegisterToPool<ITimeModeRuleService, TimeModeRuleService>(10, 100);
			G.TContainer.RegisterToPool<ITimeModeTypeService, TimeModeTypeService>(10, 100);
			G.TContainer.RegisterToPool<ITokenUserService, TokenUserService>(10, 100);
			G.TContainer.RegisterToPool<ITransactionService, TransactionService>(10, 100);
			G.TContainer.RegisterToPool<IUserService, UserService>(10, 100);
			G.TContainer.RegisterToPool<IVATOrderService, VATOrderService>(10, 100);
			G.TContainer.RegisterToPool<IVATOrderMappingService, VATOrderMappingService>(10, 100);
			G.TContainer.RegisterToPool<IViewCounterService, ViewCounterService>(10, 100);
			G.TContainer.RegisterToPool<IVoucherService, VoucherService>(10, 100);
			G.TContainer.RegisterToPool<IWardService, WardService>(10, 100);
			G.TContainer.RegisterToPool<IWebCustomerFeedbackService, WebCustomerFeedbackService>(10, 100);
			G.TContainer.RegisterToPool<IWebElementService, WebElementService>(10, 100);
			G.TContainer.RegisterToPool<IWebElementTypeService, WebElementTypeService>(10, 100);
			G.TContainer.RegisterToPool<IWebMenuService, WebMenuService>(10, 100);
			G.TContainer.RegisterToPool<IWebMenuCategoryService, WebMenuCategoryService>(10, 100);
			G.TContainer.RegisterToPool<IWebPageService, WebPageService>(10, 100);
			G.TContainer.RegisterToPool<ICustomerFeedbackService, CustomerFeedbackService>(10, 100);
		}
		
	}
}
